/**
 * translateToTagalogService.js
 *
 * Centralized translation service for English / Tagalog.
 * All UI strings are organized by component/section for easy lookup.
 *
 * Usage:
 *   import { getTranslations, getLanguage, setLanguage } from ".../translateToTagalogService";
 *   const tr = getTranslations();     // returns object for current language
 *   const tr = getTranslations("tl"); // returns Tagalog translations
 */

const STORAGE_KEY = "appLanguage";
const DEFAULT_LANGUAGE = "en";

// ─── Language helpers ────────────────────────────────────────────────────────

export const getLanguage = () =>
  localStorage.getItem(STORAGE_KEY) || DEFAULT_LANGUAGE;

export const setLanguage = (lang) => {
  localStorage.setItem(STORAGE_KEY, lang);
  window.dispatchEvent(new CustomEvent("languageChange", { detail: lang }));
};

export const toggleLanguage = () => {
  const next = getLanguage() === "en" ? "tl" : "en";
  setLanguage(next);
  return next;
};

// ─── Translations ────────────────────────────────────────────────────────────

const translations = {
  // ════════════════════════════════════════════════════════════════════════════
  //  ENGLISH
  // ════════════════════════════════════════════════════════════════════════════
  en: {
    // ── Header ──────────────────────────────────────────────────────────────
    header: {
      reportUpdates: "Report Updates",
      active: "Active",
      viewAllNotifications: "View All Notifications",
      changeTheme: "Change Theme",
      privacySettings: "Privacy Settings",
      language: "Language",
      english: "English",
      tagalog: "Tagalog",
      viewProfile: "View Profile",
      logout: "Logout",
      incidentReporting: "Incident Reporting System",
    },

    // ── Sidebar ─────────────────────────────────────────────────────────────
    sidebar: {
      incidentReporting: "Incident Reporting",
      adminPanel: "Admin Panel",
      eBarangaySystem: "E-Barangay System",
      main: "Main",
      subsystem1: "Subsystem 1",
      subsystem2: "Document Services",
      incidentComplaint: "Incident & Complaint",
      fileComplaint: "File a Complaint",
      reportIncident: "Report an Incident",
      incidentMap: "Incident Map",
      caseManagement: "Case Tracker",
      dashboard: "Dashboard",
      residents: "Residents",
      request: "Request",
      incidents: "Incidents",
      appointments: "Appointments",
      payments: "Payments",
      reports: "Analytics",
      households: "Households",
      scanner: "QR Scanner",
      certificates: "Certificates",
      support: "Support",
      userManagement: "Verification",
      settings: "Settings",
    },

    // ── Main Page ───────────────────────────────────────────────────────────
    mainPage: {
      title: "INCIDENT & COMPLAINT MANAGEMENT",
    },

    // ── Main Menu Cards ─────────────────────────────────────────────────────
    menuCards: {
      fileComplaint: "FILE A COMPLAINT",
      reportIncident: "REPORT AN INCIDENT",
      incidentMap: "INCIDENT MAP",
      incidentStatus: "CASE TRACKER",
    },

    // ── File Complaint Page ─────────────────────────────────────────────────
    fileComplaintPage: {
      title: "FILING A COMPLAINT",
      whatHappens: "WHAT HAPPENS WHEN YOU FILE A COMPLAINT?",
      whatHappensDesc:
        'Filing a formal complaint (<strong>Blotter</strong>) initiates a community-based dispute resolution process. Its primary goal is Amicable Settlement\u2014helping both parties reach a fair agreement without going to court.',
      howProcessWorks: "HOW THE PROCESS WORKS?",
      step1Title: "DOCUMENTATION",
      step1Desc:
        "Your narration will be recorded in the official Barangay Blotter. This serves as a permanent administrative record of the incident.",
      step2Title: "THE SUMMONS",
      step2Desc:
        "Within the next few days, the Barangay will issue a Notice to Appear (Summons) to the person you are complaining against (the Respondent).",
      step3Title: "MEDIATION",
      step3Desc:
        "You and the Respondent will be invited to a face-to-face meeting moderated by the Barangay Captain or a member of the Lupon Tagapamayapa.",
      step4Title: "RESOLUTION / AGREEMENT",
      step4Desc:
        "If you settle, a written agreement is signed. This has the force and effect of a court judgment.",
      step4NoAgreement:
        "<strong>No Agreement:</strong> If no settlement is reached, the Barangay will issue a Certificate to File Action (CFA). You need this document if you decide to escalate the case to a higher court or the police.",
      whatToPrepare: "WHAT TO PREPARE?",
      facts: "FACTS",
      factsDesc:
        "Clear details of the date, time, and location of the incident.",
      names: "NAMES",
      namesDesc:
        "Full names and addresses of the parties involved (if known).",
      evidence: "EVIDENCE",
      evidenceDesc:
        "Photos, videos, screenshots, or names of witnesses that can support your statement.",
      ctaButton: "FILE A COMPLAINT",
      footer:
        "Barangay Incident & Complaint Management System. All rights reserved.",
    },

    // ── Incident Report Page ────────────────────────────────────────────────
    incidentReportPage: {
      title: "REPORT A COMMUNITY INCIDENT",
      heroTitle: "HELP US MAINTAIN ORDER AND SAFETY IN OUR STREETS.",
      heroDesc:
        "Use this platform to alert the Barangay about non-emergency incidents occurring in public spaces. Your report allows our response teams (Tanods and BDRRM) to address community concerns quickly.",
      whatToReport: "WHAT TO REPORT?",
      publicSafety: "PUBLIC SAFETY & TRAFFIC",
      publicSafetyDesc:
        "Illegal parking, street obstructions, or abandoned vehicles.",
      publicNuisance: "PUBLIC NUISANCE",
      publicNuisanceDesc:
        "Excessive noise, stray/aggressive animals, or broken public facilities.",
      environmental: "ENVIRONMENTAL HAZARDS",
      environmentalDesc:
        "Sudden flooding, illegal dumping of waste, or clogged sewers.",
      health: "HEALTH HAZARDS",
      healthDesc: "Standing water (dengue risk) or unsanitary public areas.",
      howToFile: "HOW TO FILE?",
      pinLocation: "PIN THE LOCATION",
      pinLocationDesc:
        "Use the map to mark the exact spot where the incident is happening.",
      provideDesc: "PROVIDE A BRIEF DESCRIPTION",
      provideDescDesc:
        "Tell us what is happening and how long it has been occurring.",
      attachProof: "ATTACH PROOF",
      attachProofDesc:
        "A clear photo of the violation (like a vehicle's license plate or the flooded street) is essential for validation.",
      ctaButton: "REPORT AN INCIDENT",
      footer:
        "Barangay Incident & Complaint Management System. All rights reserved.",
    },

    // ── Complaint Form ──────────────────────────────────────────────────────
    complaintForm: {
      step1Title: "Basic Information",
      step1Subtitle: "When and where did this occur?",
      dateOfIncident: "Date of Incident",
      timeOfIncident: "Time of Incident",
      location: "Location / Address",
      locationPlaceholder: "e.g., Block 5 Lot 10, Street Name, Barangay",
      step2Title: "Complaint Details",
      step2Subtitle: "Describe the nature of your complaint",
      complaintType: "Type of Complaint",
      selectComplaintType: "Select complaint type",
      noise: "Noise Disturbance",
      property: "Property Dispute",
      harassment: "Harassment",
      trespassing: "Trespassing",
      parking: "Illegal Parking",
      garbage: "Garbage/Sanitation Issue",
      boundary: "Boundary Dispute",
      unpaid: "Unpaid Debt",
      other: "Other",
      severity: "Severity Level",
      selectSeverity: "Select severity",
      severityLow: "Low - Minor issue",
      severityMedium: "Medium - Moderate concern",
      severityHigh: "High - Urgent attention needed",
      description: "Detailed Description",
      descriptionPlaceholder:
        "Please provide a clear and detailed account of what happened...",
      step3Title: "Parties Involved",
      step3Subtitle: "Information about complainant and respondent",
      complainantYou: "Complainant (You)",
      fullName: "Full Name",
      yourFullName: "Your full name",
      contactNumber: "Contact Number",
      respondent: "Respondent",
      respondentName: "Name of the person",
      respondentAddress: "Address (if known)",
      respondentAddressPlaceholder: "Respondent's address or location",
      witnesses: "Witnesses (Optional)",
      witnessPlaceholder: "Witness",
      addWitness: "+ Add Another Witness",
      step4Title: "Additional Information",
      step4Subtitle: "Supporting documents and desired resolution",
      desiredResolution: "Desired Resolution",
      desiredResolutionPlaceholder:
        "What outcome are you seeking? (e.g., apology, compensation, cease of activity)",
      additionalNotes: "Additional Notes (Optional)",
      additionalNotesPlaceholder:
        "Any other information you'd like to add...",
      supportingDocuments: "Supporting Documents",
      supportingDocumentsDesc:
        "Upload any photos, videos, or documents that support your complaint",
    },

    // ── Complaint Modal ─────────────────────────────────────────────────────
    complaintModal: {
      title: "File a Complaint",
      subtitle: "Submit your complaint for barangay mediation",
      previous: "\u2190 Previous",
      next: "Next \u2192",
      step: "Step",
      of: "of",
      submit: "\u2713 Submit Complaint",
      submitting: "Submitting...",
      successTitle: "Complaint Submitted!",
      successMessage:
        "Your complaint has been recorded and will be processed by the Barangay.",
      errorSessionTitle: "Session Expired",
      errorSessionMessage: "Please log in again to continue.",
      errorTitle: "Submission Failed",
      errorMessage: "Something went wrong. Please try again.",
      dateRequired: "Date of complaint is required.",
      dateFuture: "Date cannot be in the future.",
      timeRequired: "Time of complaint is required.",
      locationRequired: "Location is required.",
      typeRequired: "Please select a complaint type.",
      severityRequired: "Please select a severity level.",
      descriptionRequired: "A detailed description is required.",
      complainantRequired: "Complainant name is required.",
      contactRequired: "Complainant contact number is required.",
      respondentRequired: "Respondent name is required.",
      coordinatesRequired: "Please pin the location on the map.",
    },

    // ── Incident Form ───────────────────────────────────────────────────────
    incidentForm: {
      step1Title: "Basic Information",
      dateOfIncident: "Date of Incident",
      timeOfIncident: "Time of Incident",
      location: "Location of Incident",
      locationPlaceholder: "Building, floor, room number, or specific area",
      step2Title: "Incident Details",
      incidentType: "Type of Incident",
      selectIncidentType: "Select incident type",
      safety: "Safety Incident",
      security: "Security Breach",
      environmental: "Environmental Hazard",
      equipment: "Equipment Failure",
      workplaceViolence: "Workplace Violence",
      fire: "Fire / Evacuation",
      accident: "Accident / Injury",
      nearMiss: "Near Miss",
      other: "Other",
      severity: "Severity Level",
      selectSeverity: "Select severity level",
      severityLow: "Low - Minor incident, no injuries",
      severityMedium: "Medium - Moderate impact, minor injuries",
      severityHigh: "High - Serious incident, significant damage",
      severityCritical: "Critical - Life-threatening, major damage",
      description: "Detailed Description",
      descriptionPlaceholder:
        "Describe what happened, including the sequence of events, circumstances, and any contributing factors...",
      immediateAction: "Immediate Action Taken",
      immediateActionPlaceholder:
        "Describe any immediate actions taken to address the incident...",
      step3Title: "People Involved",
      personsInvolved: "Persons Involved",
      personPlaceholder: "Person",
      addPerson: "Add Person",
      witnesses: "Witnesses",
      witnessPlaceholder: "Witness",
      addWitness: "Add Witness",
      impactAssessment: "Impact Assessment",
      injuries: "Were there any injuries?",
      propertyDamage: "Was there property damage?",
      medicalAttention: "Was medical attention required?",
      step4Title: "Additional Information",
      attachments: "Attachments",
      attachmentsDesc:
        "Upload photos, videos, or documents related to the incident (Max 10MB per file)",
      additionalNotes: "Additional Notes",
      additionalNotesPlaceholder:
        "Any other relevant information, recommendations, or comments...",
      reviewTitle: "Review Before Submitting",
      reviewDesc:
        "Please review all information carefully. Once submitted, this report will be sent to the safety team for investigation.",
    },

    // ── Incident Report Modal ───────────────────────────────────────────────
    incidentModal: {
      title: "Incident Report",
      subtitle: "Provide detailed information about the incident",
      previous: "\u2190 Previous",
      next: "Next \u2192",
      step: "Step",
      of: "of",
      submit: "\u2713 Submit Report",
      submitting: "Submitting...",
      successTitle: "Report Submitted!",
      successMessage:
        "Your incident report has been recorded and will be reviewed shortly.",
      errorTitle: "Submission Failed",
      errorMessage: "Something went wrong. Please try again.",
      dateRequired: "Date of incident is required.",
      dateFuture: "Date cannot be in the future.",
      timeRequired: "Time of incident is required.",
      locationRequired: "Location is required.",
      typeRequired: "Please select an incident type.",
      severityRequired: "Please select a severity level.",
      descriptionRequired: "A detailed description is required.",
      personsRequired: "At least one person involved is required.",
      witnessesRequired: "At least one witness is required.",
    },

    // ── Logout Modal ────────────────────────────────────────────────────────
    logoutModal: {
      title: "Confirm Logout",
      message:
        "Are you sure you want to sign out? You will need to log in again to access the system.",
      cancel: "Cancel",
      confirm: "Logout",
      loggingOut: "Logging out...",
    },

    // ── Theme Modal ─────────────────────────────────────────────────────────
    themeModal: {
      title: "Choose Your Theme",
      subtitle: "Customize the appearance of your workspace",
      selected: "Selected",
      oceanBlue: "Ocean Blue",
      oceanBlueDesc: "Professional and calming",
      royalPurple: "Royal Purple",
      royalPurpleDesc: "Creative and elegant",
      forestGreen: "Forest Green",
      forestGreenDesc: "Natural and refreshing",
      darkMode: "Dark Mode",
      darkModeDesc: "Easy on the eyes",
      previewNote: "Theme Preview",
      previewDesc:
        "The selected theme will be applied to your entire workspace, including buttons, cards, and navigation elements.",
      cancel: "Cancel",
      apply: "Apply Theme",
    },

    // ── Admin Landing ────────────────────────────────────────────────────────
    adminLanding: {
      overview: "Overview",
      welcomeBack: "Welcome back,",
      monitorDesc: "Monitor requests, complaints, reports, and appointment activity in real time.",
      viewAnnouncements: "View Announcements",
      analyticsDashboard: "Analytics Dashboard",
      live: "Live",
      generateInsights: "Generate Insights",
      pendingRequests: "Pending requests",
      awaitingReview: "Awaiting resident review",
      openComplaints: "Open complaints",
      activeUnresolved: "Active unresolved complaints",
      incidentReports: "Incident reports",
      filedReports: "Filed incident reports",
      pendingAppointments: "Pending appointments",
      waitingSlot: "Waiting for schedule slot",
      monthlyReports: "Monthly Reports",
      caseResolution: "Case Resolution Status",
      reportTrend: "Report Trend (14 days)",
      reportCategories: "Report Categories",
      appointmentStatus: "Appointment Status",
      monthlyAppointments: "Monthly Appointments",
      requestsVsAppointments: "Requests vs Appointments Trend",
      issuanceFactors: "Issuance Application Factors",
      issuanceFactorsDesc: "Volumes, operations, and socio-economy chart groups",
      volumes: "Volumes",
      socioEconomy: "Socio-economy",
    },

    // ── Admin Incidents ──────────────────────────────────────────────────────
    adminIncidents: {
      title: "Incident & Complaint Management",
      incidents: "Incidents",
      complaints: "Complaints",
      searchPlaceholder: "Search by description, location, type\u2026",
      filter: "Filter",
      all: "All",
      pending: "Pending",
      ongoing: "Ongoing",
      resolved: "Resolved",
      rejected: "Rejected",
      exportPDF: "Export PDF",
      noRecords: "No records found.",
      id: "ID",
      date: "Date",
      type: "Type",
      location: "Location",
      severity: "Severity",
      status: "Status",
      actions: "Actions",
      viewDetails: "View Details",
      low: "Low",
      medium: "Medium",
      high: "High",
      critical: "Critical",
      updateStatus: "Update Status",
      generateInsights: "Generate Insights",
      reportDetails: "Report Details",
      loading: "Loading\u2026",
      errorLoad: "Failed to load data.",
      updateIncidentForm: "Update Incident Form",
      updateComplaintForm: "Update Complaint Form",
      fileComplaint: "File Complaint",
      typeOfIncident: "Type of Incident",
      typeOfComplaint: "Type of Complaint",
      reportedBy: "Reported By",
      incidentId: "Incident ID",
      complaintId: "Complaint ID",
      startDate: "Start Date",
      endDate: "End Date",
      mapLegend: "Map Legend",
      downloadAsPNG: "Download as PNG",
      downloadAsPDF: "Download as PDF",
      legendResolved: "RESOLVED",
      legendResolvedDesc: "Issue has been cleared or fixed",
      legendDispatched: "DISPATCHED",
      legendDispatchedDesc: "Barangay officials dispatched on the site to check.",
      legendInProgress: "IN-PROGRESS",
      legendInProgressDesc: "Barangay officials or maintenance teams are on-site.",
      legendNewActive: "NEW / ACTIVE",
      legendNewActiveDesc: "Issue recently reported and awaiting dispatch.",
      legendRejected: "REJECTED",
      legendRejectedDesc: "Report was rejected or deemed invalid.",
      loadingReports: "Loading reports...",
      noReportsFound: "No reports found for the selected filters.",
      showingResults: "Showing {from}\u2013{to} of {total} results",
      prev: "Prev",
      next: "Next",
    },

    // ── Admin Appointments ───────────────────────────────────────────────────
    adminAppointments: {
      title: "Appointments",
      searchPlaceholder: "Search appointments\u2026",
      all: "All",
      scheduled: "Scheduled",
      rescheduled: "Rescheduled",
      completed: "Completed",
      cancelled: "Cancelled",
      noShow: "No Show",
      noAppointments: "No appointments found.",
      complainant: "Complainant",
      respondent: "Respondent",
      date: "Date",
      time: "Time",
      status: "Status",
      actions: "Actions",
      viewDetails: "View Details",
      approve: "Approve",
      reject: "Reject",
      reschedule: "Reschedule",
      loading: "Loading\u2026",
      confirmApprove: "Are you sure you want to approve this appointment?",
      confirmReject: "Are you sure you want to reject this appointment?",
      successApprove: "Appointment approved.",
      successReject: "Appointment rejected.",
      complaintId: "Complaint #",
      selectDateFirst: "Select a date first to see available slots.",
      filtered: "Filtered:",
      clear: "Clear",
      scheduleAppointment: "Schedule Appointment",
      rescheduleAppointment: "Reschedule Appointment",
      selectDate: "Select Date",
      selectTime: "Select Time",
      notes: "Notes (Optional)",
      notesPlaceholder: "Add notes for this appointment\u2026",
      saveAppointment: "Save Appointment",
      saving: "Saving\u2026",
      complaintInfo: "Complaint Information",
      complainantInfo: "Complainant",
      respondentInfo: "Respondent",
      currentSchedule: "Current Schedule",
      appointmentHistory: "Appointment History",
      noHistory: "No appointment history yet.",
      complete: "Complete",
      noShowMark: "No Show",
      confirmComplete: "Mark this appointment as completed?",
      confirmNoShow: "Mark this as no-show?",
      successComplete: "Appointment marked as completed.",
      successNoShow: "Appointment marked as no-show.",
      subtitle: "Complaint hearing appointments · Mon – Fri · 7:00 AM – 5:00 PM",
      statTotal: "TOTAL",
      statScheduled: "SCHEDULED",
      statCompleted: "COMPLETED",
      statCancelled: "CANCELLED",
      createNewAppointment: "Create New Appointment",
      from: "From",
      to: "To",
      clearFilters: "Clear Filters",
      showingAppointmentsFor: "Showing appointments for",
      apptId: "Appt ID",
      complaint: "Complaint",
      showingResults: "Showing {from}–{to} of {total} results",
      prev: "Prev",
      next: "Next",
      newDate: "New Date",
      weekdaysOnly: "(Mon – Fri only)",
      newTime: "New Time",
      timeRange: "(7:00 AM – 5:00 PM)",
      selected: "Selected:",
      slotBooked: "This slot is already booked. Please choose a different date or time.",
      autoNotify: "The complainant will be notified of this schedule change automatically.",
      confirmReschedule: "Confirm Reschedule",
      cancel: "Cancel",
      complainantLabel: "Complainant",
      respondentLabel: "Respondent",
      respondentAddress: "Respondent Address",
      appointmentId: "Appointment ID",
      description: "Description",
      markCompleted: "Mark as Completed",
      markNoShow: "Mark as No Show",
      rescheduleBtn: "Reschedule",
      confirmMarkCompleted: "Mark as Completed?",
      confirmMarkNoShow: "Mark as No Show?",
      confirmMarkCompletedMsg: "This will mark Appointment #{id} as completed. This action cannot be undone.",
      confirmMarkNoShowMsg: "This will mark Appointment #{id} as no-show. This action cannot be undone.",
      yesMarkCompleted: "Yes, Mark Completed",
      yesMarkNoShow: "Yes, Mark No Show",
      titleField: "Title",
      descriptionField: "Description",
      optional: "(optional)",
      loadingComplaints: "Loading complaints\u2026",
      selectComplaint: "Select a complaint\u2026",
      creating: "Creating\u2026",
      createAppointment: "Create Appointment",
      overdueTitle: "Appointments Requiring Action",
      overdueDesc: "{n} appointment(s) past their scheduled date",
      scheduled_label: "Scheduled",
      processing: "Processing\u2026",
      dismiss: "Dismiss",
    },

    // ── Case Management ──────────────────────────────────────────────────────
    caseManagement: {
      title: "CASE TRACKER",
      myComplaints: "My Complaints",
      myIncidents: "My Incidents",
      searchPlaceholder: "Search cases\u2026",
      noComplaints: "You have no complaints filed.",
      noIncidents: "You have no incidents reported.",
      status: "Status",
      date: "Date",
      type: "Type",
      location: "Location",
      severity: "Severity",
      viewDetails: "View Details",
      pending: "Pending",
      ongoing: "Ongoing",
      resolved: "Resolved",
      rejected: "Rejected",
      all: "All",
      loading: "Loading your cases\u2026",
      appointmentsSubtitle: "Barangay hearing appointments scheduled for your complaints",
      appointmentList: "Appointment List",
      total: "total",
      appointment: "Appointment",
      time: "Time",
      noAppointmentsFound: "No appointments found",
      noAppointmentsYet: "You have no barangay appointments yet.",
      allShown: "All {n} appointment(s) shown",
      whereToGo: "Where to Go",
      gulodBarangayHall: "Gulod Barangay Hall",
      complaintType: "Complaint Type",
      respondent: "Respondent",
      respondentAddress: "Respondent Address",
      appointmentId: "Appointment ID",
      complaintId: "Complaint ID",
      notes: "Notes",
      gridView: "Grid View",
      mapView: "Map View",
      onGoing: "On-Going",
      footer: "Barangay Incident & Complaint Management System. All rights reserved.",
    },

    // ── Incident Map ─────────────────────────────────────────────────────────
    incidentMap: {
      title: "INCIDENT MAP",
      subtitle: "Real-time map of reported incidents in the barangay",
      filterByType: "Filter by Type",
      allTypes: "All Types",
      incidents: "Incidents",
      complaints: "Complaints",
      legend: "Legend",
      noData: "No incidents to display.",
      loading: "Loading map data\u2026",
      viewReport: "View Report",
      exploreTitle: "EXPLORE THE LIVE INCIDENT MAP",
      exploreDesc: "See all the incidents and complaints you have filed, plotted directly on the Barangay Gulod map. Each pin reflects the current status of your report \u2014 red for newly submitted, orange for in-progress, and green for resolved. Click any pin to view the report title, description, and date filed.",
      incidentMapping: "INCIDENT MAPPING",
      legendNewActive: "NEW/ACTIVE",
      legendNewActiveDesc: "Issue recently reported and awaiting dispatch.",
      legendInProgress: "IN-PROGRESS",
      legendInProgressDesc: "Barangay officials or maintenance teams are on-site.",
      legendResolved: "RESOLVED",
      legendResolvedDesc: "Issue has been cleared or fixed (displayed for the last 24 hours).",
      noLocationData: "None of your submitted reports include location data, so no pins are shown.",
      footer: "Barangay Incident & Complaint Management System. All rights reserved.",
    },

    // ── Profile Page ─────────────────────────────────────────────────────────
    profilePage: {
      title: "My Profile",
      editProfile: "Edit Profile",
      save: "Save Changes",
      cancel: "Cancel",
      name: "Full Name",
      email: "Email",
      phone: "Phone Number",
      address: "Address",
      changePassword: "Change Password",
      currentPassword: "Current Password",
      newPassword: "New Password",
      confirmPassword: "Confirm New Password",
      updateSuccess: "Profile updated successfully.",
      updateError: "Failed to update profile.",
      personalInfo: "Personal Information",
      accountSettings: "Account Settings",
      profile: "Profile",
      reviewDesc: "Review your account information and security details.",
      viewProfile: "View Profile",
      barangayLogo: "Barangay Logo",
      changeProfilePhoto: "Change Profile Photo",
      cropZoomDesc: "Crop, zoom, and save your picture.",
      choosePhoto: "Choose photo",
      photoFormatDesc: "PNG or JPG up to 2MB. Camera capture supported.",
      zoom: "Zoom",
      removePhoto: "Remove photo",
      saving: "Saving...",
      updateContactInfo: "Update Contact Info",
      editContactDesc: "Edit your contact number and email address.",
      contactNumber: "Contact Number",
      emailAddress: "Email Address",
      editContactInfoBtn: "Edit Contact Info",
      viewActivityLogs: "View Activity Logs",
      refreshingProfile: "Refreshing profile details...",
      personalInfoPanel: "Personal information",
      personalInfoSubtitle: "Identity and contact details based on the user registration record.",
      residencyInfoPanel: "Residency information",
      residencyInfoSubtitle: "Registered household and barangay address.",
      accountInfoPanel: "Account information",
      accountInfoSubtitle: "System access, role, and login details.",
      firstName: "First Name",
      middleName: "Middle Name",
      lastName: "Last Name",
      suffix: "Suffix",
      contactNumberField: "Contact Number",
      emailField: "Email Address",
      birthdate: "Birthdate",
      age: "Age",
      gender: "Gender",
      nationality: "Nationality",
      maritalStatus: "Marital Status",
      sector: "Sector",
      birthRegistration: "Birth Registration",
      registeredVoter: "Registered Voter",
      houseNo: "House No.",
      purok: "Purok",
      street: "Street",
      householdPosition: "Household Position",
      residencyType: "Residency Type",
      dateStarted: "Date Started",
      fullAddress: "Full Registered Address",
      username: "Username",
      role: "Role",
      status: "Status",
      workspace: "Workspace",
      memberSince: "Member Since",
      accountProtection: "Account Protection",
    },

    // ── Change Password ──────────────────────────────────────────────────────
    changePassword: {
      title: "Change Password",
      current: "Current Password",
      new: "New Password",
      confirm: "Confirm Password",
      save: "Update Password",
      cancel: "Cancel",
      success: "Password updated successfully.",
      error: "Failed to update password.",
      mismatch: "Passwords do not match.",
    },

    // ── Sub-system 2 Main Page ───────────────────────────────────────────────
    sub2MainPage: {
      title: "DOCUMENT SERVICES",
      subtitle: "Request official barangay documents online",
      bid: "Barangay ID",
      bidDesc: "Request your official Barangay Identification Document",
      cor: "Certificate of Residency",
      corDesc: "Certify your residency in the barangay",
      coi: "Certificate of Indigency",
      coiDesc: "Certify your indigency status",
      track: "Track My Request",
      trackDesc: "Check the status of your document request",
      loading: "Loading\u2026",
    },

    // ── Sub-system 2 Admin ───────────────────────────────────────────────────
    sub2Admin: {
      title: "Document Services Analytics",
      desc: "Volumes, operations, socio-economy, and transaction insights for BID, COR, and COI requests.",
      bidCorCoiReports: "BID/COR/COI Reports",
      queueAvg: "Queue Processing Avg",
      backlogRate: "Backlog Rate",
      volumes: "Volumes",
      operations: "Operations",
      socioEconomy: "Socio-Economy",
      reports: "Reports",
      transactions: "Transactions",
      requests: "Requests",
      pending: "Pending",
      approved: "Approved",
      rejected: "Rejected",
      all: "All",
      search: "Search requests\u2026",
      noRequests: "No requests found.",
      id: "ID",
      resident: "Resident",
      type: "Document Type",
      date: "Date Requested",
      status: "Status",
      actions: "Actions",
      approve: "Approve",
      reject: "Reject",
      viewDetails: "View Details",
      loading: "Loading\u2026",
      bid: "Barangay ID",
      cor: "Certificate of Residency",
      coi: "Certificate of Indigency",
    },

    // ── Sub-system 1 ─────────────────────────────────────────────────────────
    sub1: {
      dashboard: "Dashboard",
      residents: "Residents",
      households: "Households",
      verification: "Verification",
      certificates: "Certificates",
      support: "Support",
      settings: "Settings",
      search: "Search\u2026",
      filter: "Filter",
      addNew: "Add New",
      export: "Export",
      loading: "Loading\u2026",
      noData: "No data available.",
      status: "Status",
      actions: "Actions",
      date: "Date",
      name: "Name",
      address: "Address",
      active: "Active",
      inactive: "Inactive",
      pending: "Pending",
      verified: "Verified",
      rejected: "Rejected",
      archived: "Archived",
      viewDetails: "View Details",
      edit: "Edit",
      archive: "Archive",
      restore: "Restore",
      delete: "Delete",
      confirm: "Confirm",
      cancel: "Cancel",
      save: "Save",
      close: "Close",
      totalResidents: "Total Residents",
      totalHouseholds: "Total Households",
      pendingVerifications: "Pending Verifications",
      recentActivity: "Recent Activity",
      quickActions: "Quick Actions",
      welcomeAdmin: "Welcome, Admin",
      overviewDesc: "Here's an overview of the barangay system.",
      residentsDesc: "Maintain the official masterlist, manage archived records, and review edit history from one organized workspace.",
      householdsDesc: "Manage household records, view family compositions, and track household data across the barangay.",
      refresh: "Refresh",
      registry: "Registry",
      logs: "Logs",
      addResident: "Add Resident",
      addHousehold: "Add Household",
      verificationQueue: "Verification Queue",
      approve: "Approve",
      reject: "Reject",
      certificateRequests: "Certificate Requests",
      issueCertificate: "Issue Certificate",
      supportTickets: "Support Tickets",
      resolveTicket: "Resolve Ticket",
      currentPassword: "Current Password",
      newPassword: "New Password",
      confirmPassword: "Confirm Password",
      updatePassword: "Update Password",
      themeSettings: "Theme Settings",
      languageSettings: "Language Settings",
      privacySettings: "Privacy Settings",
      barangayInfo: "Barangay Information",
      contactInfo: "Contact Information",
      operatingHours: "Operating Hours",
      verificationDesc: "Review resident identity submissions, schedule on-site visits, and finalize approvals from one clean queue.",
      certificatesDesc: "Generate official barangay certifications",
      supportDesc: "Barangay Management Technical Guide",
      settingsDesc: "Manage barangay branding settings.",
      settingsProfileDesc: "Review your personal information and security settings.",
      barangayLogo: "Barangay Logo",
      barangayLogoDesc: "Update the logo used across the portal.",
    },

    // ── Common ───────────────────────────────────────────────────────────────
    common: {
      yes: "Yes",
      no: "No",
      ok: "OK",
      submit: "Submit",
      submitting: "Submitting\u2026",
      back: "Back",
      next: "Next",
      previous: "Previous",
      done: "Done",
      error: "Error",
      success: "Success",
      warning: "Warning",
      info: "Info",
      noResults: "No results found.",
      tryAgain: "Try Again",
      loading: "Loading\u2026",
      of: "of",
      page: "Page",
      showing: "Showing",
      results: "results",
    },
  },

  // ════════════════════════════════════════════════════════════════════════════
  //  TAGALOG
  // ════════════════════════════════════════════════════════════════════════════
  tl: {
    header: {
      reportUpdates: "Mga Update ng Ulat",
      active: "Aktibo",
      viewAllNotifications: "Tingnan Lahat ng Abiso",
      changeTheme: "Baguhin ang Tema",
      privacySettings: "Mga Setting ng Privacy",
      language: "Wika",
      english: "Ingles",
      tagalog: "Tagalog",
      viewProfile: "Tingnan ang Profile",
      logout: "Mag-logout",
      incidentReporting: "Sistema ng Pag-uulat ng Insidente",
    },

    sidebar: {
      incidentReporting: "Pag-uulat ng Insidente",
      adminPanel: "Panel ng Admin",
      eBarangaySystem: "Sistema ng E-Barangay",
      main: "Pangunahin",
      subsystem1: "Subsystem 1",
      subsystem2: "Document Services",
      incidentComplaint: "Insidente at Reklamo",
      fileComplaint: "Maghain ng Reklamo",
      reportIncident: "Mag-ulat ng Insidente",
      incidentMap: "Mapa ng Insidente",
      caseManagement: "Case Tracker",
      dashboard: "Dashboard",
      residents: "Mga Residente",
      request: "Kahilingan",
      incidents: "Mga Insidente",
      appointments: "Mga Appointment",
      payments: "Mga Bayarin",
      reports: "Analytics",
      households: "Mga Sambahayan",
      scanner: "QR Scanner",
      certificates: "Mga Sertipiko",
      support: "Suporta",
      userManagement: "Verification",
      settings: "Mga Setting",
    },

    mainPage: {
      title: "PAMAMAHALA NG INSIDENTE AT REKLAMO",
    },

    menuCards: {
      fileComplaint: "MAGHAIN NG REKLAMO",
      reportIncident: "MAG-ULAT NG INSIDENTE",
      incidentMap: "MAPA NG INSIDENTE",
      incidentStatus: "CASE TRACKER",
    },

    fileComplaintPage: {
      title: "PAGHAHAIN NG REKLAMO",
      whatHappens: "ANO ANG MANGYAYARI KAPAG NAGHAIN KA NG REKLAMO?",
      whatHappensDesc:
        'Ang paghahain ng pormal na reklamo (<strong>Blotter</strong>) ay magsisimula ng proseso ng paglutas ng alitan sa komunidad. Ang pangunahing layunin nito ay Mapayapang Kasunduan\u2014matulungan ang dalawang panig na makamit ang patas na kasunduan nang hindi pumupunta sa korte.',
      howProcessWorks: "PAANO ANG PROSESO?",
      step1Title: "DOKUMENTASYON",
      step1Desc:
        "Ang iyong salaysay ay itatala sa opisyal na Barangay Blotter. Ito ay nagsisilbing permanenteng rekord ng insidente.",
      step2Title: "ANG PATAWAG",
      step2Desc:
        "Sa loob ng ilang araw, ang Barangay ay mag-iisyu ng Abiso na Humarap (Patawag) sa taong iyong inirereklamo (ang Respondent).",
      step3Title: "MEDYASYON",
      step3Desc:
        "Kayo ng Respondent ay iimbitahan sa isang harap-harapang pagpupulong na pinapangasiwaan ng Barangay Captain o isang miyembro ng Lupon Tagapamayapa.",
      step4Title: "RESOLUSYON / KASUNDUAN",
      step4Desc:
        "Kung magkakasundo, pipirmahan ang isang nakasulat na kasunduan. Ito ay may bisa at epekto ng hatol ng korte.",
      step4NoAgreement:
        "Walang Kasunduan: Kung walang napagkasunduan, ang Barangay ay mag-iisyu ng Certificate to File Action (CFA). Kailangan mo ang dokumentong ito kung magpapasya kang iakyat ang kaso sa mas mataas na hukuman o sa pulisya.",
      whatToPrepare: "ANO ANG DAPAT IHANDA?",
      facts: "MGA KATOTOHANAN",
      factsDesc:
        "Malinaw na detalye ng petsa, oras, at lokasyon ng insidente.",
      names: "MGA PANGALAN",
      namesDesc: "Buong pangalan at tirahan ng mga sangkot (kung alam).",
      evidence: "MGA EBIDENSYA",
      evidenceDesc:
        "Mga litrato, video, screenshot, o pangalan ng mga saksi na makakasuporta sa iyong pahayag.",
      ctaButton: "MAGHAIN NG REKLAMO",
      footer:
        "Sistema ng Pamamahala ng Insidente at Reklamo ng Barangay. Lahat ng karapatan ay nakalaan.",
    },

    incidentReportPage: {
      title: "MAG-ULAT NG INSIDENTE SA KOMUNIDAD",
      heroTitle:
        "TULUNGAN KAMING PANATILIHIN ANG KAAYUSAN AT KALIGTASAN SA ATING MGA KALYE.",
      heroDesc:
        "Gamitin ang platform na ito upang alertuhan ang Barangay tungkol sa mga hindi-emerhensiyang insidente sa mga pampublikong lugar. Ang iyong ulat ay nagbibigay-daan sa aming mga response team (Tanod at BDRRM) na matugunan ang mga alalahanin ng komunidad nang mabilis.",
      whatToReport: "ANO ANG DAPAT IULAT?",
      publicSafety: "KALIGTASANG PUBLIKO AT TRAPIKO",
      publicSafetyDesc:
        "Ilegal na paradahan, harang sa kalsada, o mga inabandunang sasakyan.",
      publicNuisance: "ABALA SA PUBLIKO",
      publicNuisanceDesc:
        "Labis na ingay, mga gala/agresibong hayop, o mga sirang pampublikong pasilidad.",
      environmental: "MGA PANGANIB SA KAPALIGIRAN",
      environmentalDesc:
        "Biglaang pagbaha, ilegal na pagtatapon ng basura, o baradong imburnal.",
      health: "MGA PANGANIB SA KALUSUGAN",
      healthDesc:
        "Nakatigil na tubig (panganib ng dengue) o hindi malinis na mga pampublikong lugar.",
      howToFile: "PAANO MAG-FILE?",
      pinLocation: "I-PIN ANG LOKASYON",
      pinLocationDesc:
        "Gamitin ang mapa upang markahan ang eksaktong lugar kung saan nangyayari ang insidente.",
      provideDesc: "MAGBIGAY NG MAIKLING PAGLALARAWAN",
      provideDescDesc:
        "Sabihin sa amin kung ano ang nangyayari at gaano na ito katagal.",
      attachProof: "MAG-ATTACH NG EBIDENSYA",
      attachProofDesc:
        "Mahalaga ang malinaw na larawan ng paglabag (tulad ng plaka ng sasakyan o binabahang kalye) para sa pagpapatunay.",
      ctaButton: "MAG-ULAT NG INSIDENTE",
      footer:
        "Sistema ng Pamamahala ng Insidente at Reklamo ng Barangay. Lahat ng karapatan ay nakalaan.",
    },

    complaintForm: {
      step1Title: "Pangunahing Impormasyon",
      step1Subtitle: "Kailan at saan ito naganap?",
      dateOfIncident: "Petsa ng Insidente",
      timeOfIncident: "Oras ng Insidente",
      location: "Lokasyon / Tirahan",
      locationPlaceholder: "hal., Block 5 Lot 10, Pangalan ng Kalye, Barangay",
      step2Title: "Mga Detalye ng Reklamo",
      step2Subtitle: "Ilarawan ang uri ng iyong reklamo",
      complaintType: "Uri ng Reklamo",
      selectComplaintType: "Pumili ng uri ng reklamo",
      noise: "Kaguluhan sa Ingay",
      property: "Alitan sa Ari-arian",
      harassment: "Panliligalig",
      trespassing: "Pagpasok sa Pribadong Ari-arian",
      parking: "Ilegal na Paradahan",
      garbage: "Problema sa Basura/Sanitasyon",
      boundary: "Alitan sa Hangganan",
      unpaid: "Hindi Nabayarang Utang",
      other: "Iba Pa",
      severity: "Antas ng Kalubhaan",
      selectSeverity: "Pumili ng kalubhaan",
      severityLow: "Mababa - Maliit na isyu",
      severityMedium: "Katamtaman - Katamtamang alalahanin",
      severityHigh: "Mataas - Kailangang madaliang tugunan",
      description: "Detalyadong Paglalarawan",
      descriptionPlaceholder:
        "Mangyaring magbigay ng malinaw at detalyadong salaysay ng nangyari...",
      step3Title: "Mga Sangkot na Partido",
      step3Subtitle: "Impormasyon tungkol sa nagreklamo at respondent",
      complainantYou: "Nagreklamo (Ikaw)",
      fullName: "Buong Pangalan",
      yourFullName: "Iyong buong pangalan",
      contactNumber: "Numero ng Telepono",
      respondent: "Respondent",
      respondentName: "Pangalan ng tao",
      respondentAddress: "Tirahan (kung alam)",
      respondentAddressPlaceholder: "Tirahan o lokasyon ng respondent",
      witnesses: "Mga Saksi (Opsyonal)",
      witnessPlaceholder: "Saksi",
      addWitness: "+ Magdagdag ng Saksi",
      step4Title: "Karagdagang Impormasyon",
      step4Subtitle: "Mga sumusuportang dokumento at ninanais na resolusyon",
      desiredResolution: "Ninanais na Resolusyon",
      desiredResolutionPlaceholder:
        "Ano ang hinahanap mong resulta? (hal., paghingi ng tawad, kabayaran, paghinto ng aktibidad)",
      additionalNotes: "Karagdagang Tala (Opsyonal)",
      additionalNotesPlaceholder:
        "Anumang iba pang impormasyon na nais mong idagdag...",
      supportingDocuments: "Mga Sumusuportang Dokumento",
      supportingDocumentsDesc:
        "Mag-upload ng mga litrato, video, o dokumento na sumusuporta sa iyong reklamo",
    },

    complaintModal: {
      title: "Maghain ng Reklamo",
      subtitle: "Isumite ang iyong reklamo para sa medyasyon ng barangay",
      previous: "\u2190 Nakaraan",
      next: "Susunod \u2192",
      step: "Hakbang",
      of: "ng",
      submit: "\u2713 Isumite ang Reklamo",
      submitting: "Isinusumite...",
      successTitle: "Naisumite na ang Reklamo!",
      successMessage:
        "Ang iyong reklamo ay naitala na at ipoproseso ng Barangay.",
      errorSessionTitle: "Nag-expire ang Session",
      errorSessionMessage: "Mangyaring mag-login muli upang magpatuloy.",
      errorTitle: "Nabigo ang Pagsusumite",
      errorMessage: "May nangyaring mali. Mangyaring subukan muli.",
      dateRequired: "Kinakailangan ang petsa ng reklamo.",
      dateFuture: "Hindi maaaring nasa hinaharap ang petsa.",
      timeRequired: "Kinakailangan ang oras ng reklamo.",
      locationRequired: "Kinakailangan ang lokasyon.",
      typeRequired: "Mangyaring pumili ng uri ng reklamo.",
      severityRequired: "Mangyaring pumili ng antas ng kalubhaan.",
      descriptionRequired: "Kinakailangan ang detalyadong paglalarawan.",
      complainantRequired: "Kinakailangan ang pangalan ng nagreklamo.",
      contactRequired: "Kinakailangan ang contact number ng nagreklamo.",
      respondentRequired: "Kinakailangan ang pangalan ng respondent.",
      coordinatesRequired: "Mangyaring i-pin ang lokasyon sa mapa.",
    },

    incidentForm: {
      step1Title: "Pangunahing Impormasyon",
      dateOfIncident: "Petsa ng Insidente",
      timeOfIncident: "Oras ng Insidente",
      location: "Lokasyon ng Insidente",
      locationPlaceholder: "Gusali, palapag, numero ng silid, o tiyak na lugar",
      step2Title: "Mga Detalye ng Insidente",
      incidentType: "Uri ng Insidente",
      selectIncidentType: "Pumili ng uri ng insidente",
      safety: "Insidente sa Kaligtasan",
      security: "Paglabag sa Seguridad",
      environmental: "Panganib sa Kapaligiran",
      equipment: "Sira ng Kagamitan",
      workplaceViolence: "Karahasan sa Trabaho",
      fire: "Sunog / Ebakwasyon",
      accident: "Aksidente / Pinsala",
      nearMiss: "Halos Aksidente",
      other: "Iba Pa",
      severity: "Antas ng Kalubhaan",
      selectSeverity: "Pumili ng antas ng kalubhaan",
      severityLow: "Mababa - Maliit na insidente, walang sugatan",
      severityMedium: "Katamtaman - Katamtamang epekto, maliit na sugat",
      severityHigh: "Mataas - Seryosong insidente, malaking pinsala",
      severityCritical: "Kritikal - Nakamamatay, malaking pinsala",
      description: "Detalyadong Paglalarawan",
      descriptionPlaceholder:
        "Ilarawan kung ano ang nangyari, kasama ang pagkakasunud-sunod ng mga pangyayari, mga kalagayan, at mga nakapag-ambag na kadahilanan...",
      immediateAction: "Agarang Aksyong Ginawa",
      immediateActionPlaceholder:
        "Ilarawan ang anumang agarang aksyong ginawa upang tugunan ang insidente...",
      step3Title: "Mga Taong Sangkot",
      personsInvolved: "Mga Taong Sangkot",
      personPlaceholder: "Tao",
      addPerson: "Magdagdag ng Tao",
      witnesses: "Mga Saksi",
      witnessPlaceholder: "Saksi",
      addWitness: "Magdagdag ng Saksi",
      impactAssessment: "Pagtatasa ng Epekto",
      injuries: "May nasaktan ba?",
      propertyDamage: "May nasira bang ari-arian?",
      medicalAttention: "Kailangan ba ng atensyong medikal?",
      step4Title: "Karagdagang Impormasyon",
      attachments: "Mga Kalakip",
      attachmentsDesc:
        "Mag-upload ng mga litrato, video, o dokumento na may kaugnayan sa insidente (Max 10MB bawat file)",
      additionalNotes: "Karagdagang Tala",
      additionalNotesPlaceholder:
        "Anumang iba pang kaugnay na impormasyon, rekomendasyon, o komento...",
      reviewTitle: "Suriin Bago Isumite",
      reviewDesc:
        "Mangyaring suriin nang mabuti ang lahat ng impormasyon. Kapag naisumite na, ang ulat na ito ay ipapadala sa safety team para sa imbestigasyon.",
    },

    incidentModal: {
      title: "Ulat ng Insidente",
      subtitle: "Magbigay ng detalyadong impormasyon tungkol sa insidente",
      previous: "\u2190 Nakaraan",
      next: "Susunod \u2192",
      step: "Hakbang",
      of: "ng",
      submit: "\u2713 Isumite ang Ulat",
      submitting: "Isinusumite...",
      successTitle: "Naisumite na ang Ulat!",
      successMessage:
        "Ang iyong ulat ng insidente ay naitala na at susuriin sa lalong madaling panahon.",
      errorTitle: "Nabigo ang Pagsusumite",
      errorMessage: "May nangyaring mali. Mangyaring subukan muli.",
      dateRequired: "Kinakailangan ang petsa ng insidente.",
      dateFuture: "Hindi maaaring nasa hinaharap ang petsa.",
      timeRequired: "Kinakailangan ang oras ng insidente.",
      locationRequired: "Kinakailangan ang lokasyon.",
      typeRequired: "Mangyaring pumili ng uri ng insidente.",
      severityRequired: "Mangyaring pumili ng antas ng kalubhaan.",
      descriptionRequired: "Kinakailangan ang detalyadong paglalarawan.",
      personsRequired: "Kinakailangan ang kahit isang taong sangkot.",
      witnessesRequired: "Kinakailangan ang kahit isang saksi.",
    },

    logoutModal: {
      title: "Kumpirmahin ang Pag-logout",
      message:
        "Sigurado ka bang gusto mong mag-sign out? Kailangan mong mag-login muli upang ma-access ang sistema.",
      cancel: "Kanselahin",
      confirm: "Oo, Mag-logout",
      loggingOut: "Nagla-logout...",
    },

    themeModal: {
      title: "Pumili ng Tema",
      subtitle: "I-customize ang hitsura ng iyong workspace",
      selected: "Napili",
      oceanBlue: "Asul ng Karagatan",
      oceanBlueDesc: "Propesyonal at nakakapagpahinga",
      royalPurple: "Maharlikang Lila",
      royalPurpleDesc: "Malikhain at elegante",
      forestGreen: "Berdeng Kagubatan",
      forestGreenDesc: "Natural at nakakapag-refresh",
      darkMode: "Madilim na Mode",
      darkModeDesc: "Madali sa mata",
      previewNote: "Preview ng Tema",
      previewDesc:
        "Ang napiling tema ay ilalapat sa buong workspace mo, kasama ang mga button, card, at navigation element.",
      cancel: "Kanselahin",
      apply: "Ilapat ang Tema",
    },

    // ── Admin Landing ────────────────────────────────────────────────────────
    adminLanding: {
      overview: "Pangkalahatang-tanaw",
      welcomeBack: "Maligayang pagbabalik,",
      monitorDesc: "Subaybayan ang mga kahilingan, reklamo, ulat, at aktibidad ng appointment nang real time.",
      viewAnnouncements: "Tingnan ang Mga Anunsyo",
      analyticsDashboard: "Dashboard ng Analytics",
      live: "Live",
      generateInsights: "Gumawa ng Mga Insight",
      pendingRequests: "Mga nakabinbing kahilingan",
      awaitingReview: "Naghihintay ng pagsusuri ng residente",
      openComplaints: "Mga bukas na reklamo",
      activeUnresolved: "Mga aktibong hindi pa naresolba",
      incidentReports: "Mga ulat ng insidente",
      filedReports: "Mga isinampa na ulat ng insidente",
      pendingAppointments: "Mga nakabinbing appointment",
      waitingSlot: "Naghihintay ng time slot",
      monthlyReports: "Buwanang Ulat",
      caseResolution: "Katayuan ng Resolusyon ng Kaso",
      reportTrend: "Trend ng Ulat (14 araw)",
      reportCategories: "Mga Kategorya ng Ulat",
      appointmentStatus: "Katayuan ng Appointment",
      monthlyAppointments: "Buwanang Mga Appointment",
      requestsVsAppointments: "Trend ng Mga Kahilingan kumpara sa Appointment",
      issuanceFactors: "Mga Salik sa Aplikasyon ng Issuance",
      issuanceFactorsDesc: "Mga grupo ng tsart ng volume, operasyon, at sosyo-ekonomiya",
      volumes: "Mga Volume",
      socioEconomy: "Sosyo-ekonomiya",
    },

    // ── Admin Incidents ──────────────────────────────────────────────────────
    adminIncidents: {
      title: "Pamamahala ng Insidente at Reklamo",
      incidents: "Mga Insidente",
      complaints: "Mga Reklamo",
      searchPlaceholder: "Maghanap ayon sa paglalarawan, lokasyon, uri\u2026",
      filter: "Filter",
      all: "Lahat",
      pending: "Nakabinbin",
      ongoing: "Nagpapatuloy",
      resolved: "Naresolba",
      rejected: "Tinanggihan",
      exportPDF: "I-export ang PDF",
      noRecords: "Walang nahanap na rekord.",
      id: "ID",
      date: "Petsa",
      type: "Uri",
      location: "Lokasyon",
      severity: "Kalubhaan",
      status: "Katayuan",
      actions: "Mga Aksyon",
      viewDetails: "Tingnan ang Detalye",
      low: "Mababa",
      medium: "Katamtaman",
      high: "Mataas",
      critical: "Kritikal",
      updateStatus: "I-update ang Katayuan",
      generateInsights: "Gumawa ng Mga Insight",
      reportDetails: "Mga Detalye ng Ulat",
      loading: "Naglo-load\u2026",
      errorLoad: "Nabigo ang pag-load ng data.",
      updateIncidentForm: "I-update ang Form ng Insidente",
      updateComplaintForm: "I-update ang Form ng Reklamo",
      fileComplaint: "Maghain ng Reklamo",
      typeOfIncident: "Uri ng Insidente",
      typeOfComplaint: "Uri ng Reklamo",
      reportedBy: "Iniulat Ni",
      incidentId: "ID ng Insidente",
      complaintId: "ID ng Reklamo",
      startDate: "Simula ng Petsa",
      endDate: "Katapusan ng Petsa",
      mapLegend: "Paliwanag ng Mapa",
      downloadAsPNG: "I-download bilang PNG",
      downloadAsPDF: "I-download bilang PDF",
      legendResolved: "NARESOLBA",
      legendResolvedDesc: "Ang isyu ay nalinis o naayos na",
      legendDispatched: "NAPADALA",
      legendDispatchedDesc: "Ang mga opisyal ng barangay ay napadala sa lugar upang suriin.",
      legendInProgress: "IN-PROGRESS",
      legendInProgressDesc: "Ang mga opisyal ng barangay o mga maintenance team ay nasa lugar.",
      legendNewActive: "BAGO / AKTIBO",
      legendNewActiveDesc: "Isyu na kamakailan lamang na iniulat at naghihintay ng pagpapadala.",
      legendRejected: "TINANGGIHAN",
      legendRejectedDesc: "Ang ulat ay tinanggihan o itinuturing na hindi wasto.",
      loadingReports: "Naglo-load ng mga ulat...",
      noReportsFound: "Walang nahanap na ulat para sa mga napiling filter.",
      showingResults: "Ipinapakita ang {from}\u2013{to} ng {total} resulta",
      prev: "Nakaraan",
      next: "Susunod",
    },

    // ── Admin Appointments ───────────────────────────────────────────────────
    adminAppointments: {
      title: "Mga Appointment",
      searchPlaceholder: "Maghanap ng appointment\u2026",
      all: "Lahat",
      scheduled: "Naka-iskedyul",
      rescheduled: "Muling Naka-iskedyul",
      completed: "Natapos",
      cancelled: "Nakansela",
      noShow: "Hindi Dumating",
      noAppointments: "Walang nahanap na appointment.",
      complainant: "Nagreklamo",
      respondent: "Respondent",
      date: "Petsa",
      time: "Oras",
      status: "Katayuan",
      actions: "Mga Aksyon",
      viewDetails: "Tingnan ang Detalye",
      approve: "Aprubahan",
      reject: "Tanggihan",
      reschedule: "Muling Iskedyulin",
      loading: "Naglo-load\u2026",
      confirmApprove: "Sigurado ka bang gusto mong aprubahan ang appointment na ito?",
      confirmReject: "Sigurado ka bang gusto mong tanggihan ang appointment na ito?",
      successApprove: "Naaprubahan ang appointment.",
      successReject: "Natanggihan ang appointment.",
      complaintId: "Reklamo #",
      selectDateFirst: "Pumili muna ng petsa upang makita ang mga available na slot.",
      filtered: "Naka-filter:",
      clear: "I-clear",
      scheduleAppointment: "Mag-iskedyul ng Appointment",
      rescheduleAppointment: "Muling Mag-iskedyul ng Appointment",
      selectDate: "Pumili ng Petsa",
      selectTime: "Pumili ng Oras",
      notes: "Mga Tala (Opsyonal)",
      notesPlaceholder: "Magdagdag ng mga tala para sa appointment na ito\u2026",
      saveAppointment: "I-save ang Appointment",
      saving: "Nagse-save\u2026",
      complaintInfo: "Impormasyon ng Reklamo",
      complainantInfo: "Nagreklamo",
      respondentInfo: "Respondent",
      currentSchedule: "Kasalukuyang Iskedyul",
      appointmentHistory: "Kasaysayan ng Appointment",
      noHistory: "Wala pang kasaysayan ng appointment.",
      complete: "Tapusin",
      noShowMark: "Markahan bilang Hindi Dumating",
      confirmComplete: "Markahan ang appointment na ito bilang natapos?",
      confirmNoShow: "Markahan ito bilang hindi dumating?",
      successComplete: "Ang appointment ay minarkahan bilang natapos.",
      successNoShow: "Ang appointment ay minarkahan bilang hindi dumating.",
      subtitle: "Mga hearing ng reklamo · Lun – Biy · 7:00 AM – 5:00 PM",
      statTotal: "KABUUAN",
      statScheduled: "NAKA-ISKEDYUL",
      statCompleted: "NATAPOS",
      statCancelled: "NAKANSELA",
      createNewAppointment: "Lumikha ng Bagong Appointment",
      from: "Mula",
      to: "Hanggang",
      clearFilters: "I-clear ang Mga Filter",
      showingAppointmentsFor: "Ipinapakita ang mga appointment para sa",
      apptId: "ID ng Appt",
      complaint: "Reklamo",
      showingResults: "Ipinapakita ang {from}–{to} ng {total} resulta",
      prev: "Nakaraan",
      next: "Susunod",
      newDate: "Bagong Petsa",
      weekdaysOnly: "(Lun – Biy lamang)",
      newTime: "Bagong Oras",
      timeRange: "(7:00 AM – 5:00 PM)",
      selected: "Napili:",
      slotBooked: "Ang slot na ito ay nakalaan na. Mangyaring pumili ng ibang petsa o oras.",
      autoNotify: "Awtomatikong aabisuhan ang nagreklamo tungkol sa pagbabago ng iskedyul.",
      confirmReschedule: "Kumpirmahin ang Muling Pag-iskedyul",
      cancel: "Kanselahin",
      complainantLabel: "Nagreklamo",
      respondentLabel: "Respondent",
      respondentAddress: "Tirahan ng Respondent",
      appointmentId: "ID ng Appointment",
      description: "Paglalarawan",
      markCompleted: "Markahan bilang Natapos",
      markNoShow: "Markahan bilang Hindi Dumating",
      rescheduleBtn: "Muling Iskedyulin",
      confirmMarkCompleted: "Markahan bilang Natapos?",
      confirmMarkNoShow: "Markahan bilang Hindi Dumating?",
      confirmMarkCompletedMsg: "Ito ay magmamarka ng Appointment #{id} bilang natapos. Hindi na ito mababawi.",
      confirmMarkNoShowMsg: "Ito ay magmamarka ng Appointment #{id} bilang hindi dumating. Hindi na ito mababawi.",
      yesMarkCompleted: "Oo, Markahan bilang Natapos",
      yesMarkNoShow: "Oo, Markahan bilang Hindi Dumating",
      titleField: "Pamagat",
      descriptionField: "Paglalarawan",
      optional: "(opsyonal)",
      loadingComplaints: "Naglo-load ng mga reklamo\u2026",
      selectComplaint: "Pumili ng reklamo\u2026",
      creating: "Lumilikha\u2026",
      createAppointment: "Lumikha ng Appointment",
      overdueTitle: "Mga Appointment na Nangangailangan ng Aksyon",
      overdueDesc: "{n} appointment ang nakaraan na sa nakatakdang petsa",
      scheduled_label: "Naka-iskedyul",
      processing: "Pinoproseso\u2026",
      dismiss: "Isara",
    },

    // ── Case Management ──────────────────────────────────────────────────────
    caseManagement: {
      title: "CASE TRACKER",
      myComplaints: "Aking mga Reklamo",
      myIncidents: "Aking mga Insidente",
      searchPlaceholder: "Maghanap ng kaso\u2026",
      noComplaints: "Wala kang naghain na reklamo.",
      noIncidents: "Wala kang naiulat na insidente.",
      status: "Katayuan",
      date: "Petsa",
      type: "Uri",
      location: "Lokasyon",
      severity: "Kalubhaan",
      viewDetails: "Tingnan ang Detalye",
      pending: "Nakabinbin",
      ongoing: "Nagpapatuloy",
      resolved: "Naresolba",
      rejected: "Tinanggihan",
      all: "Lahat",
      loading: "Nilo-load ang iyong mga kaso\u2026",
      appointmentsSubtitle: "Mga appointment sa pagdinig ng barangay para sa iyong mga reklamo",
      appointmentList: "Listahan ng Appointment",
      total: "kabuuan",
      appointment: "Appointment",
      time: "Oras",
      noAppointmentsFound: "Walang nahanap na appointment",
      noAppointmentsYet: "Wala ka pang appointment sa barangay.",
      allShown: "Lahat ng {n} appointment ay ipinapakita",
      whereToGo: "Saan Pumunta",
      gulodBarangayHall: "Gulod Barangay Hall",
      complaintType: "Uri ng Reklamo",
      respondent: "Respondent",
      respondentAddress: "Tirahan ng Respondent",
      appointmentId: "ID ng Appointment",
      complaintId: "ID ng Reklamo",
      notes: "Mga Tala",
      gridView: "Grid View",
      mapView: "Map View",
      onGoing: "Nagpapatuloy",
      footer: "Sistema ng Pamamahala ng Insidente at Reklamo ng Barangay. Lahat ng karapatan ay nakalaan.",
    },

    // ── Incident Map ─────────────────────────────────────────────────────────
    incidentMap: {
      title: "MAPA NG INSIDENTE",
      subtitle: "Real-time na mapa ng mga iniulat na insidente sa barangay",
      filterByType: "I-filter ayon sa Uri",
      allTypes: "Lahat ng Uri",
      incidents: "Mga Insidente",
      complaints: "Mga Reklamo",
      legend: "Paliwanag",
      noData: "Walang insidenteng ipapakita.",
      loading: "Naglo-load ng datos ng mapa\u2026",
      viewReport: "Tingnan ang Ulat",
      exploreTitle: "TUKLASIN ANG LIVE NA MAPA NG INSIDENTE",
      exploreDesc: "Tingnan ang lahat ng insidente at reklamo na iyong inihain, na nakalagay sa mapa ng Barangay Gulod. Ang bawat pin ay sumasalamin sa kasalukuyang katayuan ng iyong ulat \u2014 pula para sa bagong isinumite, orange para sa in-progress, at berde para sa naresolba. I-click ang anumang pin upang makita ang pamagat, paglalarawan, at petsa ng ulat.",
      incidentMapping: "PAGMAMAPA NG INSIDENTE",
      legendNewActive: "BAGO/AKTIBO",
      legendNewActiveDesc: "Isyu na kamakailan lamang na iniulat at naghihintay ng pagpapadala.",
      legendInProgress: "IN-PROGRESS",
      legendInProgressDesc: "Ang mga opisyal ng barangay o mga maintenance team ay nasa lugar.",
      legendResolved: "NARESOLBA",
      legendResolvedDesc: "Ang isyu ay nalinis o naayos na (ipinapakita sa loob ng huling 24 na oras).",
      noLocationData: "Wala sa iyong mga isinumiteng ulat ang may datos ng lokasyon, kaya walang mga pin na ipinapakita.",
      footer: "Sistema ng Pamamahala ng Insidente at Reklamo ng Barangay. Lahat ng karapatan ay nakalaan.",
    },

    // ── Profile Page ─────────────────────────────────────────────────────────
    profilePage: {
      title: "Aking Profile",
      editProfile: "I-edit ang Profile",
      save: "I-save ang Mga Pagbabago",
      cancel: "Kanselahin",
      name: "Buong Pangalan",
      email: "Email",
      phone: "Numero ng Telepono",
      address: "Tirahan",
      changePassword: "Baguhin ang Password",
      currentPassword: "Kasalukuyang Password",
      newPassword: "Bagong Password",
      confirmPassword: "Kumpirmahin ang Bagong Password",
      updateSuccess: "Matagumpay na na-update ang profile.",
      updateError: "Nabigo ang pag-update ng profile.",
      personalInfo: "Personal na Impormasyon",
      accountSettings: "Mga Setting ng Account",
      profile: "Profile",
      reviewDesc: "Suriin ang iyong impormasyon sa account at mga detalye ng seguridad.",
      viewProfile: "Tingnan ang Profile",
      barangayLogo: "Logo ng Barangay",
      changeProfilePhoto: "Baguhin ang Profile Photo",
      cropZoomDesc: "I-crop, i-zoom, at i-save ang iyong larawan.",
      choosePhoto: "Pumili ng larawan",
      photoFormatDesc: "PNG o JPG hanggang 2MB. Sinusuportahan ang camera capture.",
      zoom: "Zoom",
      removePhoto: "Alisin ang larawan",
      saving: "Nagse-save...",
      updateContactInfo: "I-update ang Impormasyon sa Pakikipag-ugnayan",
      editContactDesc: "I-edit ang iyong numero ng telepono at email address.",
      contactNumber: "Numero ng Telepono",
      emailAddress: "Email Address",
      editContactInfoBtn: "I-edit ang Impormasyon sa Pakikipag-ugnayan",
      viewActivityLogs: "Tingnan ang Mga Activity Log",
      refreshingProfile: "Ine-refresh ang mga detalye ng profile...",
      personalInfoPanel: "Personal na impormasyon",
      personalInfoSubtitle: "Pagkakakilanlan at mga detalye ng pakikipag-ugnayan batay sa talaan ng pagpaparehistro ng gumagamit.",
      residencyInfoPanel: "Impormasyon sa paninirahan",
      residencyInfoSubtitle: "Nairehistrong sambahayan at tirahan sa barangay.",
      accountInfoPanel: "Impormasyon ng account",
      accountInfoSubtitle: "Pag-access sa sistema, tungkulin, at mga detalye ng pag-login.",
      firstName: "Pangalan",
      middleName: "Gitnang Pangalan",
      lastName: "Apelyido",
      suffix: "Suffix",
      contactNumberField: "Numero ng Telepono",
      emailField: "Email Address",
      birthdate: "Petsa ng Kapanganakan",
      age: "Edad",
      gender: "Kasarian",
      nationality: "Nasyonalidad",
      maritalStatus: "Katayuan sa Sibil",
      sector: "Sektor",
      birthRegistration: "Pagpaparehistro ng Kapanganakan",
      registeredVoter: "Rehistradong Botante",
      houseNo: "Blg. ng Bahay",
      purok: "Purok",
      street: "Kalye",
      householdPosition: "Posisyon sa Sambahayan",
      residencyType: "Uri ng Paninirahan",
      dateStarted: "Petsa ng Simula",
      fullAddress: "Buong Nairehistrong Tirahan",
      username: "Username",
      role: "Tungkulin",
      status: "Katayuan",
      workspace: "Workspace",
      memberSince: "Miyembro Mula",
      accountProtection: "Proteksyon ng Account",
    },

    // ── Change Password ──────────────────────────────────────────────────────
    changePassword: {
      title: "Baguhin ang Password",
      current: "Kasalukuyang Password",
      new: "Bagong Password",
      confirm: "Kumpirmahin ang Password",
      save: "I-update ang Password",
      cancel: "Kanselahin",
      success: "Matagumpay na na-update ang password.",
      error: "Nabigo ang pag-update ng password.",
      mismatch: "Hindi magkatugma ang mga password.",
    },

    // ── Sub-system 2 Main Page ───────────────────────────────────────────────
    sub2MainPage: {
      title: "MGA SERBISYO SA DOKUMENTO",
      subtitle: "Humiling ng opisyal na dokumento ng barangay online",
      bid: "Barangay ID",
      bidDesc: "Humiling ng iyong opisyal na Barangay Identification Document",
      cor: "Certificate of Residency",
      corDesc: "Patunayan ang iyong paninirahan sa barangay",
      coi: "Certificate of Indigency",
      coiDesc: "Patunayan ang iyong katayuang indigent",
      track: "Subaybayan ang Aking Kahilingan",
      trackDesc: "Tingnan ang katayuan ng iyong kahilingan sa dokumento",
      loading: "Naglo-load\u2026",
    },

    // ── Sub-system 2 Admin ───────────────────────────────────────────────────
    sub2Admin: {
      title: "Analytics ng Mga Serbisyo sa Dokumento",
      desc: "Mga insights sa dami, operasyon, sosyo-ekonomiya, at transaksyon para sa BID, COR, at COI na mga kahilingan.",
      bidCorCoiReports: "Mga Ulat BID/COR/COI",
      queueAvg: "Average ng Pagproseso ng Pila",
      backlogRate: "Rate ng Backlog",
      volumes: "Mga Dami",
      operations: "Mga Operasyon",
      socioEconomy: "Sosyo-Ekonomiya",
      reports: "Mga Ulat",
      transactions: "Mga Transaksyon",
      requests: "Mga Kahilingan",
      pending: "Nakabinbin",
      approved: "Naaprubahan",
      rejected: "Tinanggihan",
      all: "Lahat",
      search: "Maghanap ng kahilingan\u2026",
      noRequests: "Walang nahanap na kahilingan.",
      id: "ID",
      resident: "Residente",
      type: "Uri ng Dokumento",
      date: "Petsa ng Kahilingan",
      status: "Katayuan",
      actions: "Mga Aksyon",
      approve: "Aprubahan",
      reject: "Tanggihan",
      viewDetails: "Tingnan ang Detalye",
      loading: "Naglo-load\u2026",
      bid: "Barangay ID",
      cor: "Certificate of Residency",
      coi: "Certificate of Indigency",
    },

    // ── Sub-system 1 ─────────────────────────────────────────────────────────
    sub1: {
      dashboard: "Dashboard",
      residents: "Mga Residente",
      households: "Mga Sambahayan",
      verification: "Verification",
      certificates: "Mga Sertipiko",
      support: "Suporta",
      settings: "Mga Setting",
      search: "Maghanap\u2026",
      filter: "Filter",
      addNew: "Magdagdag",
      export: "I-export",
      loading: "Naglo-load\u2026",
      noData: "Walang available na data.",
      status: "Katayuan",
      actions: "Mga Aksyon",
      date: "Petsa",
      name: "Pangalan",
      address: "Tirahan",
      active: "Aktibo",
      inactive: "Hindi Aktibo",
      pending: "Nakabinbin",
      verified: "Na-verify",
      rejected: "Tinanggihan",
      archived: "Naka-archive",
      viewDetails: "Tingnan ang Detalye",
      edit: "I-edit",
      archive: "I-archive",
      restore: "Ibalik",
      delete: "Burahin",
      confirm: "Kumpirmahin",
      cancel: "Kanselahin",
      save: "I-save",
      close: "Isara",
      totalResidents: "Kabuuang Mga Residente",
      totalHouseholds: "Kabuuang Mga Sambahayan",
      pendingVerifications: "Mga Nakabinbing Verification",
      recentActivity: "Kamakailang Aktibidad",
      quickActions: "Mabilis na Aksyon",
      welcomeAdmin: "Maligayang pagdating, Admin",
      overviewDesc: "Narito ang pangkalahatang-tanaw ng sistema ng barangay.",
      residentsDesc: "Panatilihin ang opisyal na masterlist, pamahalaan ang mga naka-archive na rekord, at suriin ang kasaysayan ng pag-edit mula sa isang organisadong workspace.",
      householdsDesc: "Pamahalaan ang mga rekord ng sambahayan, tingnan ang mga komposisyon ng pamilya, at subaybayan ang datos ng sambahayan sa buong barangay.",
      refresh: "I-refresh",
      registry: "Talaan",
      logs: "Mga Log",
      addResident: "Magdagdag ng Residente",
      addHousehold: "Magdagdag ng Sambahayan",
      verificationQueue: "Pila sa Verification",
      approve: "Aprubahan",
      reject: "Tanggihan",
      certificateRequests: "Mga Kahilingan sa Sertipiko",
      issueCertificate: "Mag-isyu ng Sertipiko",
      supportTickets: "Mga Support Ticket",
      resolveTicket: "Resolbahin ang Ticket",
      currentPassword: "Kasalukuyang Password",
      newPassword: "Bagong Password",
      confirmPassword: "Kumpirmahin ang Password",
      updatePassword: "I-update ang Password",
      themeSettings: "Mga Setting ng Tema",
      languageSettings: "Mga Setting ng Wika",
      privacySettings: "Mga Setting ng Privacy",
      barangayInfo: "Impormasyon ng Barangay",
      contactInfo: "Impormasyon sa Pakikipag-ugnayan",
      operatingHours: "Mga Oras ng Operasyon",
      verificationDesc: "Suriin ang mga isinumiteng pagkakakilanlan ng residente, mag-iskedyul ng mga on-site na bisita, at tapusin ang mga pag-apruba mula sa isang maayos na pila.",
      certificatesDesc: "Mag-generate ng mga opisyal na sertipiko ng barangay",
      supportDesc: "Teknikal na Gabay sa Pamamahala ng Barangay",
      settingsDesc: "Pamahalaan ang mga setting ng branding ng barangay.",
      settingsProfileDesc: "Suriin ang iyong personal na impormasyon at mga setting ng seguridad.",
      barangayLogo: "Logo ng Barangay",
      barangayLogoDesc: "I-update ang logo na ginagamit sa buong portal.",
    },

    // ── Common ───────────────────────────────────────────────────────────────
    common: {
      yes: "Oo",
      no: "Hindi",
      ok: "OK",
      submit: "Isumite",
      submitting: "Isinusumite\u2026",
      back: "Bumalik",
      next: "Susunod",
      previous: "Nakaraan",
      done: "Tapos",
      error: "Error",
      success: "Matagumpay",
      warning: "Babala",
      info: "Impormasyon",
      noResults: "Walang nahanap na resulta.",
      tryAgain: "Subukan Muli",
      loading: "Naglo-load\u2026",
      of: "ng",
      page: "Pahina",
      showing: "Nagpapakita",
      results: "mga resulta",
    },
  },
};

// ─── Public API ──────────────────────────────────────────────────────────────

/**
 * Get the full translations object for the given (or current) language.
 * @param {string} [lang] - "en" or "tl". Falls back to stored preference.
 */
export const getTranslations = (lang) => {
  const key = lang || getLanguage();
  return translations[key] || translations.en;
};

export default translations;
