const themeTokens = {
  blue: {
    // Page & cards
    pageBg: "bg-gradient-to-br from-slate-100 via-slate-50 to-blue-50",
    cardBg: "bg-white",
    cardText: "text-slate-800",
    cardBorder: "border-slate-200",
    subtleText: "text-slate-600",

    // Primary gradient (buttons, logo, badges)
    primaryGrad: "from-blue-600 to-indigo-600",
    primarySolid: "bg-blue-600",
    primaryHover: "hover:bg-blue-700",
    primaryText: "text-blue-600",
    primaryLight: "bg-blue-50",
    primaryLightHover: "hover:bg-blue-100",
    primaryRing: "focus:ring-blue-500",
    primaryBorder: "focus:border-blue-500",
    primaryHoverBorder: "hover:border-blue-400",

    // Progress / indicator
    progressGrad: "from-blue-500 to-indigo-500",
    stepActiveBg: "from-blue-600 to-indigo-600",
    stepCompleteBg: "from-blue-500 to-indigo-500",
    stepActiveRing: "ring-blue-100",
    stepInactiveBg: "bg-white",
    stepInactiveText: "text-slate-400",
    stepInactiveBorder: "border-slate-300",
    stepLabelActive: "text-slate-700",
    stepLabelInactive: "text-slate-400",
    mobileStepText: "text-slate-700",
    mobileStepSubtext: "text-slate-500",

    // Modal header
    modalHeaderGrad: "from-blue-50 to-indigo-50",
    modalHeaderIcon: "text-blue-600",

    // Modal shell
    modalBg: "bg-white",
    modalTitle: "text-slate-800",
    modalSubtext: "text-slate-600",
    modalCloseBtnColor: "text-slate-400",
    modalCloseBtnHover: "hover:text-slate-600",
    modalCloseBtnHoverBg: "hover:bg-white",
    modalHeaderBorderBottom: "border-slate-200",

    // Progress section strip
    progressSectionBg: "bg-slate-50",
    progressSectionBorder: "border-slate-100",

    // Footer
    footerBg: "bg-slate-50",
    footerBorder: "border-slate-200",
    footerPrevDisabledBg: "bg-slate-200",
    footerPrevDisabledText: "text-slate-400",
    footerPrevActiveBg: "bg-slate-700",
    footerPrevActiveText: "text-white",
    footerPrevActiveHover: "hover:bg-slate-800",
    footerStepText: "text-slate-600",

    // Footer buttons
    nextBtnBg: "bg-blue-600",
    nextBtnHover: "hover:bg-blue-700",
    submitGrad: "from-blue-600 to-indigo-600",
    submitDisabled: "bg-blue-400",

    // Form step icons (bg + icon colour)
    step1Bg: "bg-blue-100",
    step1Icon: "text-blue-600",
    step2Bg: "bg-amber-100",
    step2Icon: "text-amber-600",
    step3Bg: "bg-purple-100",
    step3Icon: "text-purple-600",
    step4Bg: "bg-green-100",
    step4Icon: "text-green-600",

    // Form headings / labels
    stepHeading: "text-slate-800",
    labelText: "text-slate-700",
    sectionTitle: "text-slate-700",

    // Form inputs (shared base)
    formInputBg: "bg-white",
    formInputText: "text-slate-900",
    formInputPlaceholder: "placeholder-slate-400",
    formInputBorder: "border-slate-300",

    // Remove-button in person/witness lists
    removeBtn: "text-slate-400",
    removeBtnHoverText: "hover:text-red-500",
    removeBtnHoverBg: "hover:bg-red-50",

    // Impact assessment section
    impactSectionBorder: "border-slate-200",
    impactSectionTitle: "text-slate-700",
    impactCheckboxBg: "bg-slate-50",

    // Info banner (Step 4)
    bannerBg: "bg-blue-50",
    bannerBorder: "border-blue-500",
    bannerIcon: "text-blue-600",
    bannerTitle: "text-blue-800",
    bannerText: "text-blue-700",

    // Add-person / add-witness buttons
    addBtnText: "text-blue-600",
    addBtnHoverText: "hover:text-blue-700",
    addBtnHoverBg: "hover:bg-blue-50",

    // Checkbox accent
    checkboxAccent: "text-blue-600",
    checkboxRing: "focus:ring-blue-500",
    checkboxBorder: "border-slate-300",
    checkboxLabelText: "text-slate-700",
    checkboxLabelHover: "group-hover:text-slate-900",

    // File upload drag zone
    dragBorder: "border-blue-500",
    dragBg: "bg-blue-50",
    dragHoverBorder: "hover:border-blue-400",
    dragDefaultBorder: "border-slate-300",
    dragDefaultHoverBg: "hover:bg-slate-50",
    fileUploadLabelText: "text-slate-700",
    fileUploadDescText: "text-slate-500",
    fileUploadIconColor: "text-slate-400",
    fileUploadTextPrimary: "text-slate-700",
    fileUploadTextSecondary: "text-slate-500",
    fileListItemBg: "bg-slate-50",
    fileListItemBorder: "border-slate-200",
    fileListItemHoverBg: "hover:bg-slate-100",
    fileListItemNameText: "text-slate-700",
    fileListItemSizeText: "text-slate-500",
    fileListRemoveBtn: "text-slate-400",

    // ── Sidebar ──────────────────────────────────────────────────────────
    sidebarBg: "bg-slate-50",
    sidebarBorder: "border-slate-200",
    sidebarText: "text-slate-500",
    sidebarActiveText: "text-blue-700",
    sidebarActiveBg: "bg-blue-50",
    sidebarActiveBorder: "border-blue-600",
    sidebarHoverBg: "hover:bg-slate-100",
    sidebarIconActive: "text-blue-600",
    sidebarAppName: "text-slate-800",

    // ── ThemeModal ───────────────────────────────────────────────────────
    themeModalBg: "bg-white",
    themeModalInfoBg: "bg-blue-50",
    themeModalInfoBorder: "border-blue-200",
    themeModalInfoIcon: "text-blue-600",
    themeModalInfoTitle: "text-blue-900",
    themeModalInfoText: "text-blue-700",
    themeModalFooterBg: "bg-slate-50",
    themeModalFooterBorder: "border-slate-200",
    themeModalCancelText: "text-slate-600",
    themeModalCancelHoverText: "hover:text-slate-800",
    themeModalCancelHoverBg: "hover:bg-slate-200",
    themeModalCardBorder: "border-slate-200",
    themeModalCardHoverBorder: "hover:border-slate-300",
    themeModalCardInfoBg: "bg-white",
    themeModalCardName: "text-slate-800",
    themeModalCardDesc: "text-slate-600",

    // ── Toast ────────────────────────────────────────────────────────────
    toastCloseBtn: "text-slate-400",
    toastCloseBtnHover: "hover:text-slate-600",
  },

  purple: {
    pageBg: "bg-gradient-to-br from-slate-100 via-slate-50 to-purple-50",
    cardBg: "bg-white",
    cardText: "text-slate-800",
    cardBorder: "border-slate-200",
    subtleText: "text-slate-600",

    primaryGrad: "from-purple-600 to-pink-600",
    primarySolid: "bg-purple-600",
    primaryHover: "hover:bg-purple-700",
    primaryText: "text-purple-600",
    primaryLight: "bg-purple-50",
    primaryLightHover: "hover:bg-purple-100",
    primaryRing: "focus:ring-purple-500",
    primaryBorder: "focus:border-purple-500",
    primaryHoverBorder: "hover:border-purple-400",

    progressGrad: "from-purple-500 to-pink-500",
    stepActiveBg: "from-purple-600 to-pink-600",
    stepCompleteBg: "from-purple-500 to-pink-500",
    stepActiveRing: "ring-purple-100",
    stepInactiveBg: "bg-white",
    stepInactiveText: "text-slate-400",
    stepInactiveBorder: "border-slate-300",
    stepLabelActive: "text-slate-700",
    stepLabelInactive: "text-slate-400",
    mobileStepText: "text-slate-700",
    mobileStepSubtext: "text-slate-500",

    modalHeaderGrad: "from-purple-50 to-pink-50",
    modalHeaderIcon: "text-purple-600",
    modalBg: "bg-white",
    modalTitle: "text-slate-800",
    modalSubtext: "text-slate-600",
    modalCloseBtnColor: "text-slate-400",
    modalCloseBtnHover: "hover:text-slate-600",
    modalCloseBtnHoverBg: "hover:bg-white",
    modalHeaderBorderBottom: "border-slate-200",
    progressSectionBg: "bg-slate-50",
    progressSectionBorder: "border-slate-100",
    footerBg: "bg-slate-50",
    footerBorder: "border-slate-200",
    footerPrevDisabledBg: "bg-slate-200",
    footerPrevDisabledText: "text-slate-400",
    footerPrevActiveBg: "bg-slate-700",
    footerPrevActiveText: "text-white",
    footerPrevActiveHover: "hover:bg-slate-800",
    footerStepText: "text-slate-600",

    nextBtnBg: "bg-purple-600",
    nextBtnHover: "hover:bg-purple-700",
    submitGrad: "from-purple-600 to-pink-600",
    submitDisabled: "bg-purple-400",

    step1Bg: "bg-purple-100",
    step1Icon: "text-purple-600",
    step2Bg: "bg-amber-100",
    step2Icon: "text-amber-600",
    step3Bg: "bg-pink-100",
    step3Icon: "text-pink-600",
    step4Bg: "bg-green-100",
    step4Icon: "text-green-600",

    stepHeading: "text-slate-800",
    labelText: "text-slate-700",
    sectionTitle: "text-slate-700",
    formInputBg: "bg-white",
    formInputText: "text-slate-900",
    formInputPlaceholder: "placeholder-slate-400",
    formInputBorder: "border-slate-300",
    removeBtn: "text-slate-400",
    removeBtnHoverText: "hover:text-red-500",
    removeBtnHoverBg: "hover:bg-red-50",
    impactSectionBorder: "border-slate-200",
    impactSectionTitle: "text-slate-700",
    impactCheckboxBg: "bg-slate-50",

    bannerBg: "bg-purple-50",
    bannerBorder: "border-purple-500",
    bannerIcon: "text-purple-600",
    bannerTitle: "text-purple-800",
    bannerText: "text-purple-700",

    addBtnText: "text-purple-600",
    addBtnHoverText: "hover:text-purple-700",
    addBtnHoverBg: "hover:bg-purple-50",

    checkboxAccent: "text-purple-600",
    checkboxRing: "focus:ring-purple-500",
    checkboxBorder: "border-slate-300",
    checkboxLabelText: "text-slate-700",
    checkboxLabelHover: "group-hover:text-slate-900",

    dragBorder: "border-purple-500",
    dragBg: "bg-purple-50",
    dragHoverBorder: "hover:border-purple-400",
    dragDefaultBorder: "border-slate-300",
    dragDefaultHoverBg: "hover:bg-slate-50",
    fileUploadLabelText: "text-slate-700",
    fileUploadDescText: "text-slate-500",
    fileUploadIconColor: "text-slate-400",
    fileUploadTextPrimary: "text-slate-700",
    fileUploadTextSecondary: "text-slate-500",
    fileListItemBg: "bg-slate-50",
    fileListItemBorder: "border-slate-200",
    fileListItemHoverBg: "hover:bg-slate-100",
    fileListItemNameText: "text-slate-700",
    fileListItemSizeText: "text-slate-500",
    fileListRemoveBtn: "text-slate-400",

    sidebarBg: "bg-slate-50",
    sidebarBorder: "border-slate-200",
    sidebarText: "text-slate-500",
    sidebarActiveText: "text-purple-700",
    sidebarActiveBg: "bg-purple-50",
    sidebarActiveBorder: "border-purple-600",
    sidebarHoverBg: "hover:bg-slate-100",
    sidebarIconActive: "text-purple-600",
    sidebarAppName: "text-slate-800",

    themeModalBg: "bg-white",
    themeModalInfoBg: "bg-blue-50",
    themeModalInfoBorder: "border-blue-200",
    themeModalInfoIcon: "text-blue-600",
    themeModalInfoTitle: "text-blue-900",
    themeModalInfoText: "text-blue-700",
    themeModalFooterBg: "bg-slate-50",
    themeModalFooterBorder: "border-slate-200",
    themeModalCancelText: "text-slate-600",
    themeModalCancelHoverText: "hover:text-slate-800",
    themeModalCancelHoverBg: "hover:bg-slate-200",
    themeModalCardBorder: "border-slate-200",
    themeModalCardHoverBorder: "hover:border-slate-300",
    themeModalCardInfoBg: "bg-white",
    themeModalCardName: "text-slate-800",
    themeModalCardDesc: "text-slate-600",

    toastCloseBtn: "text-slate-400",
    toastCloseBtnHover: "hover:text-slate-600",
  },

  green: {
    pageBg: "bg-gradient-to-br from-slate-100 via-slate-50 to-green-50",
    cardBg: "bg-white",
    cardText: "text-slate-800",
    cardBorder: "border-slate-200",
    subtleText: "text-slate-600",

    primaryGrad: "from-green-600 to-emerald-600",
    primarySolid: "bg-green-600",
    primaryHover: "hover:bg-green-700",
    primaryText: "text-green-600",
    primaryLight: "bg-green-50",
    primaryLightHover: "hover:bg-green-100",
    primaryRing: "focus:ring-green-500",
    primaryBorder: "focus:border-green-500",
    primaryHoverBorder: "hover:border-green-400",

    progressGrad: "from-green-500 to-emerald-500",
    stepActiveBg: "from-green-600 to-emerald-600",
    stepCompleteBg: "from-green-500 to-emerald-500",
    stepActiveRing: "ring-green-100",
    stepInactiveBg: "bg-white",
    stepInactiveText: "text-slate-400",
    stepInactiveBorder: "border-slate-300",
    stepLabelActive: "text-slate-700",
    stepLabelInactive: "text-slate-400",
    mobileStepText: "text-slate-700",
    mobileStepSubtext: "text-slate-500",

    modalHeaderGrad: "from-green-50 to-emerald-50",
    modalHeaderIcon: "text-green-600",
    modalBg: "bg-white",
    modalTitle: "text-slate-800",
    modalSubtext: "text-slate-600",
    modalCloseBtnColor: "text-slate-400",
    modalCloseBtnHover: "hover:text-slate-600",
    modalCloseBtnHoverBg: "hover:bg-white",
    modalHeaderBorderBottom: "border-slate-200",
    progressSectionBg: "bg-slate-50",
    progressSectionBorder: "border-slate-100",
    footerBg: "bg-slate-50",
    footerBorder: "border-slate-200",
    footerPrevDisabledBg: "bg-slate-200",
    footerPrevDisabledText: "text-slate-400",
    footerPrevActiveBg: "bg-slate-700",
    footerPrevActiveText: "text-white",
    footerPrevActiveHover: "hover:bg-slate-800",
    footerStepText: "text-slate-600",

    nextBtnBg: "bg-green-600",
    nextBtnHover: "hover:bg-green-700",
    submitGrad: "from-green-600 to-emerald-600",
    submitDisabled: "bg-green-400",

    step1Bg: "bg-green-100",
    step1Icon: "text-green-600",
    step2Bg: "bg-amber-100",
    step2Icon: "text-amber-600",
    step3Bg: "bg-emerald-100",
    step3Icon: "text-emerald-600",
    step4Bg: "bg-teal-100",
    step4Icon: "text-teal-600",

    stepHeading: "text-slate-800",
    labelText: "text-slate-700",
    sectionTitle: "text-slate-700",
    formInputBg: "bg-white",
    formInputText: "text-slate-900",
    formInputPlaceholder: "placeholder-slate-400",
    formInputBorder: "border-slate-300",
    removeBtn: "text-slate-400",
    removeBtnHoverText: "hover:text-red-500",
    removeBtnHoverBg: "hover:bg-red-50",
    impactSectionBorder: "border-slate-200",
    impactSectionTitle: "text-slate-700",
    impactCheckboxBg: "bg-slate-50",

    bannerBg: "bg-green-50",
    bannerBorder: "border-green-500",
    bannerIcon: "text-green-600",
    bannerTitle: "text-green-800",
    bannerText: "text-green-700",

    addBtnText: "text-green-600",
    addBtnHoverText: "hover:text-green-700",
    addBtnHoverBg: "hover:bg-green-50",

    checkboxAccent: "text-green-600",
    checkboxRing: "focus:ring-green-500",
    checkboxBorder: "border-slate-300",
    checkboxLabelText: "text-slate-700",
    checkboxLabelHover: "group-hover:text-slate-900",

    dragBorder: "border-green-500",
    dragBg: "bg-green-50",
    dragHoverBorder: "hover:border-green-400",
    dragDefaultBorder: "border-slate-300",
    dragDefaultHoverBg: "hover:bg-slate-50",
    fileUploadLabelText: "text-slate-700",
    fileUploadDescText: "text-slate-500",
    fileUploadIconColor: "text-slate-400",
    fileUploadTextPrimary: "text-slate-700",
    fileUploadTextSecondary: "text-slate-500",
    fileListItemBg: "bg-slate-50",
    fileListItemBorder: "border-slate-200",
    fileListItemHoverBg: "hover:bg-slate-100",
    fileListItemNameText: "text-slate-700",
    fileListItemSizeText: "text-slate-500",
    fileListRemoveBtn: "text-slate-400",

    sidebarBg: "bg-slate-50",
    sidebarBorder: "border-slate-200",
    sidebarText: "text-slate-500",
    sidebarActiveText: "text-green-700",
    sidebarActiveBg: "bg-green-50",
    sidebarActiveBorder: "border-green-600",
    sidebarHoverBg: "hover:bg-slate-100",
    sidebarIconActive: "text-green-600",
    sidebarAppName: "text-slate-800",

    themeModalBg: "bg-white",
    themeModalInfoBg: "bg-blue-50",
    themeModalInfoBorder: "border-blue-200",
    themeModalInfoIcon: "text-blue-600",
    themeModalInfoTitle: "text-blue-900",
    themeModalInfoText: "text-blue-700",
    themeModalFooterBg: "bg-slate-50",
    themeModalFooterBorder: "border-slate-200",
    themeModalCancelText: "text-slate-600",
    themeModalCancelHoverText: "hover:text-slate-800",
    themeModalCancelHoverBg: "hover:bg-slate-200",
    themeModalCardBorder: "border-slate-200",
    themeModalCardHoverBorder: "hover:border-slate-300",
    themeModalCardInfoBg: "bg-white",
    themeModalCardName: "text-slate-800",
    themeModalCardDesc: "text-slate-600",

    toastCloseBtn: "text-slate-400",
    toastCloseBtnHover: "hover:text-slate-600",
  },

  dark: {
    pageBg: "bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900",
    cardBg: "bg-slate-800",
    cardText: "text-slate-100",
    cardBorder: "border-slate-700",
    subtleText: "text-slate-300",

    primaryGrad: "from-slate-600 to-indigo-700",
    primarySolid: "bg-slate-600",
    primaryHover: "hover:bg-slate-500",
    primaryText: "text-indigo-400",
    primaryLight: "bg-slate-700",
    primaryLightHover: "hover:bg-slate-600",
    primaryRing: "focus:ring-indigo-500",
    primaryBorder: "focus:border-indigo-500",
    primaryHoverBorder: "hover:border-indigo-400",

    progressGrad: "from-indigo-500 to-slate-500",
    stepActiveBg: "from-indigo-600 to-slate-600",
    stepCompleteBg: "from-indigo-500 to-slate-500",
    stepActiveRing: "ring-indigo-900",
    stepInactiveBg: "bg-slate-700",
    stepInactiveText: "text-slate-500",
    stepInactiveBorder: "border-slate-600",
    stepLabelActive: "text-slate-200",
    stepLabelInactive: "text-slate-500",
    mobileStepText: "text-slate-200",
    mobileStepSubtext: "text-slate-500",

    modalHeaderGrad: "from-slate-700 to-slate-800",
    modalHeaderIcon: "text-indigo-400",
    modalBg: "bg-slate-800",
    modalTitle: "text-slate-100",
    modalSubtext: "text-slate-400",
    modalCloseBtnColor: "text-slate-500",
    modalCloseBtnHover: "hover:text-slate-300",
    modalCloseBtnHoverBg: "hover:bg-slate-700",
    modalHeaderBorderBottom: "border-slate-700",
    progressSectionBg: "bg-slate-750",
    progressSectionBorder: "border-slate-700",
    footerBg: "bg-slate-900",
    footerBorder: "border-slate-700",
    footerPrevDisabledBg: "bg-slate-700",
    footerPrevDisabledText: "text-slate-500",
    footerPrevActiveBg: "bg-slate-600",
    footerPrevActiveText: "text-white",
    footerPrevActiveHover: "hover:bg-slate-500",
    footerStepText: "text-slate-400",

    nextBtnBg: "bg-indigo-600",
    nextBtnHover: "hover:bg-indigo-700",
    submitGrad: "from-indigo-600 to-slate-700",
    submitDisabled: "bg-indigo-400",

    step1Bg: "bg-indigo-900",
    step1Icon: "text-indigo-400",
    step2Bg: "bg-amber-900",
    step2Icon: "text-amber-400",
    step3Bg: "bg-purple-900",
    step3Icon: "text-purple-400",
    step4Bg: "bg-emerald-900",
    step4Icon: "text-emerald-400",

    stepHeading: "text-slate-100",
    labelText: "text-slate-300",
    sectionTitle: "text-slate-300",
    formInputBg: "bg-slate-700",
    formInputText: "text-slate-100",
    formInputPlaceholder: "placeholder-slate-500",
    formInputBorder: "border-slate-600",
    removeBtn: "text-slate-500",
    removeBtnHoverText: "hover:text-red-400",
    removeBtnHoverBg: "hover:bg-slate-700",
    impactSectionBorder: "border-slate-700",
    impactSectionTitle: "text-slate-300",
    impactCheckboxBg: "bg-slate-700",

    bannerBg: "bg-slate-700",
    bannerBorder: "border-indigo-500",
    bannerIcon: "text-indigo-400",
    bannerTitle: "text-indigo-300",
    bannerText: "text-slate-300",

    addBtnText: "text-indigo-400",
    addBtnHoverText: "hover:text-indigo-300",
    addBtnHoverBg: "hover:bg-slate-700",

    checkboxAccent: "text-indigo-500",
    checkboxRing: "focus:ring-indigo-500",
    checkboxBorder: "border-slate-600",
    checkboxLabelText: "text-slate-300",
    checkboxLabelHover: "group-hover:text-slate-100",

    dragBorder: "border-indigo-500",
    dragBg: "bg-slate-700",
    dragHoverBorder: "hover:border-indigo-400",
    dragDefaultBorder: "border-slate-600",
    dragDefaultHoverBg: "hover:bg-slate-700",
    fileUploadLabelText: "text-slate-300",
    fileUploadDescText: "text-slate-500",
    fileUploadIconColor: "text-slate-500",
    fileUploadTextPrimary: "text-slate-200",
    fileUploadTextSecondary: "text-slate-500",
    fileListItemBg: "bg-slate-700",
    fileListItemBorder: "border-slate-600",
    fileListItemHoverBg: "hover:bg-slate-600",
    fileListItemNameText: "text-slate-200",
    fileListItemSizeText: "text-slate-500",
    fileListRemoveBtn: "text-slate-500",

    // ── Sidebar ──────────────────────────────────────────────────────────
    sidebarBg: "bg-slate-900",
    sidebarBorder: "border-slate-700",
    sidebarText: "text-slate-400",
    sidebarActiveText: "text-indigo-300",
    sidebarActiveBg: "bg-slate-800",
    sidebarActiveBorder: "border-indigo-500",
    sidebarHoverBg: "hover:bg-slate-800",
    sidebarIconActive: "text-indigo-400",
    sidebarAppName: "text-slate-100",

    // ── ThemeModal ───────────────────────────────────────────────────────
    themeModalBg: "bg-slate-800",
    themeModalInfoBg: "bg-slate-700",
    themeModalInfoBorder: "border-indigo-600",
    themeModalInfoIcon: "text-indigo-400",
    themeModalInfoTitle: "text-indigo-300",
    themeModalInfoText: "text-slate-300",
    themeModalFooterBg: "bg-slate-900",
    themeModalFooterBorder: "border-slate-700",
    themeModalCancelText: "text-slate-300",
    themeModalCancelHoverText: "hover:text-slate-100",
    themeModalCancelHoverBg: "hover:bg-slate-700",
    themeModalCardBorder: "border-slate-600",
    themeModalCardHoverBorder: "hover:border-slate-500",
    themeModalCardInfoBg: "bg-slate-700",
    themeModalCardName: "text-slate-100",
    themeModalCardDesc: "text-slate-400",

    // ── Toast ────────────────────────────────────────────────────────────
    toastCloseBtn: "text-slate-500",
    toastCloseBtnHover: "hover:text-slate-300",
  },
};

export default themeTokens;
