const themeTokens = {
  blue: {
    // Page & cards
    pageBg: "bg-gradient-to-br from-slate-100 via-slate-50 to-blue-50",
    cardBg: "bg-white",
    cardText: "text-slate-800",
    cardBorder: "border-slate-200",
    subtleText: "text-slate-600",

    // Primary gradient (buttons, logo, badges)
    primaryGrad: "from-blue-600 to-indigo-600",
    primarySolid: "bg-blue-600",
    primaryHover: "hover:bg-blue-700",
    primaryText: "text-blue-600",
    primaryLight: "bg-blue-50",
    primaryLightHover: "hover:bg-blue-100",
    primaryRing: "focus:ring-blue-500",
    primaryBorder: "focus:border-blue-500",
    primaryHoverBorder: "hover:border-blue-400",

    // Progress / indicator
    progressGrad: "from-blue-500 to-indigo-500",
    stepActiveBg: "from-blue-600 to-indigo-600",
    stepCompleteBg: "from-blue-500 to-indigo-500",
    stepActiveRing: "ring-blue-100",
    progressTrackBg: "bg-slate-200",
    stepInactiveBg: "bg-white",
    stepInactiveBorder: "border-slate-300",
    stepInactiveText: "text-slate-400",
    stepLabelActive: "text-slate-700",
    stepLabelInactive: "text-slate-400",

    // Modal
    modalBg: "bg-white",
    modalHeaderGrad: "from-indigo-100 to-blue-50",
    modalHeaderIcon: "text-blue-600",
    modalTitle: "text-slate-800",
    modalSubtext: "text-slate-600",
    modalHeaderBorderBottom: "border-blue-200",
    modalCloseBtnColor: "text-slate-500",
    modalCloseBtnHover: "hover:text-slate-700",
    modalCloseBtnHoverBg: "hover:bg-slate-100",

    // Progress section (inside modal)
    progressSectionBg: "bg-slate-50",
    progressSectionBorder: "border-slate-200",

    // Footer
    footerBg: "bg-slate-50",
    footerBorder: "border-slate-200",
    footerStepText: "text-slate-500",
    footerPrevActiveBg: "bg-white",
    footerPrevActiveText: "text-slate-700",
    footerPrevActiveHover: "hover:bg-slate-100",
    footerPrevDisabledBg: "bg-slate-100",
    footerPrevDisabledText: "text-slate-400",

    // Footer buttons
    nextBtnBg: "bg-blue-600",
    nextBtnHover: "hover:bg-blue-700",
    submitGrad: "from-blue-600 to-indigo-600",
    submitDisabled: "bg-blue-400",

    // Form fields
    inputBg: "bg-white",
    inputText: "text-slate-900",
    inputPlaceholder: "placeholder-slate-400",
    inputBorder: "border-slate-300",
    labelText: "text-slate-700",
    sectionTitle: "text-slate-800",
    sectionSubtitle: "text-slate-700",
    dividerBorder: "border-slate-200",
    inlineBg: "bg-slate-50",
    removeBtn: "text-slate-400 hover:text-red-500 hover:bg-red-50",

    // Form step icons (bg + icon colour)
    step1Bg: "bg-blue-100",
    step1Icon: "text-blue-600",
    step2Bg: "bg-amber-100",
    step2Icon: "text-amber-600",
    step3Bg: "bg-purple-100",
    step3Icon: "text-purple-600",
    step4Bg: "bg-green-100",
    step4Icon: "text-green-600",

    // Info banner (Step 4)
    bannerBg: "bg-blue-50",
    bannerBorder: "border-blue-500",
    bannerIcon: "text-blue-600",
    bannerTitle: "text-blue-800",
    bannerText: "text-blue-700",

    // Add-person / add-witness buttons
    addBtnText: "text-blue-600",
    addBtnHoverText: "hover:text-blue-700",
    addBtnHoverBg: "hover:bg-blue-50",

    // Checkbox accent
    checkboxAccent: "text-blue-600",
    checkboxRing: "focus:ring-blue-500",

    // File upload drag zone
    dragBorder: "border-blue-500",
    dragBg: "bg-blue-50",
    dragHoverBorder: "hover:border-blue-400",

    // ── Sidebar ──────────────────────────────────────────────
    sidebarBg: "bg-slate-50",
    sidebarBorder: "border-slate-200",
    sidebarText: "text-slate-500",
    sidebarActiveText: "text-blue-700",
    sidebarActiveBg: "bg-blue-50",
    sidebarActiveBorder: "border-blue-600",
    sidebarHoverBg: "hover:bg-slate-100",
    sidebarIconActive: "text-blue-600",
  },

  purple: {
    pageBg: "bg-gradient-to-br from-slate-100 via-slate-50 to-purple-50",
    cardBg: "bg-white",
    cardText: "text-slate-800",
    cardBorder: "border-slate-200",
    subtleText: "text-slate-600",

    primaryGrad: "from-purple-600 to-pink-600",
    primarySolid: "bg-purple-600",
    primaryHover: "hover:bg-purple-700",
    primaryText: "text-purple-600",
    primaryLight: "bg-purple-50",
    primaryLightHover: "hover:bg-purple-100",
    primaryRing: "focus:ring-purple-500",
    primaryBorder: "focus:border-purple-500",
    primaryHoverBorder: "hover:border-purple-400",

    progressGrad: "from-purple-500 to-pink-500",
    stepActiveBg: "from-purple-600 to-pink-600",
    stepCompleteBg: "from-purple-500 to-pink-500",
    stepActiveRing: "ring-purple-100",
    progressTrackBg: "bg-slate-200",
    stepInactiveBg: "bg-white",
    stepInactiveBorder: "border-slate-300",
    stepInactiveText: "text-slate-400",
    stepLabelActive: "text-slate-700",
    stepLabelInactive: "text-slate-400",

    modalBg: "bg-white",
    modalHeaderGrad: "from-pink-100 to-purple-50",
    modalHeaderIcon: "text-purple-600",
    modalTitle: "text-slate-800",
    modalSubtext: "text-slate-600",
    modalHeaderBorderBottom: "border-purple-200",
    modalCloseBtnColor: "text-slate-500",
    modalCloseBtnHover: "hover:text-slate-700",
    modalCloseBtnHoverBg: "hover:bg-slate-100",

    progressSectionBg: "bg-slate-50",
    progressSectionBorder: "border-slate-200",

    footerBg: "bg-slate-50",
    footerBorder: "border-slate-200",
    footerStepText: "text-slate-500",
    footerPrevActiveBg: "bg-white",
    footerPrevActiveText: "text-slate-700",
    footerPrevActiveHover: "hover:bg-slate-100",
    footerPrevDisabledBg: "bg-slate-100",
    footerPrevDisabledText: "text-slate-400",

    nextBtnBg: "bg-purple-600",
    nextBtnHover: "hover:bg-purple-700",
    submitGrad: "from-purple-600 to-pink-600",
    submitDisabled: "bg-purple-400",

    inputBg: "bg-white",
    inputText: "text-slate-900",
    inputPlaceholder: "placeholder-slate-400",
    inputBorder: "border-slate-300",
    labelText: "text-slate-700",
    sectionTitle: "text-slate-800",
    sectionSubtitle: "text-slate-700",
    dividerBorder: "border-slate-200",
    inlineBg: "bg-slate-50",
    removeBtn: "text-slate-400 hover:text-red-500 hover:bg-red-50",

    step1Bg: "bg-purple-100",
    step1Icon: "text-purple-600",
    step2Bg: "bg-amber-100",
    step2Icon: "text-amber-600",
    step3Bg: "bg-pink-100",
    step3Icon: "text-pink-600",
    step4Bg: "bg-green-100",
    step4Icon: "text-green-600",

    bannerBg: "bg-purple-50",
    bannerBorder: "border-purple-500",
    bannerIcon: "text-purple-600",
    bannerTitle: "text-purple-800",
    bannerText: "text-purple-700",

    addBtnText: "text-purple-600",
    addBtnHoverText: "hover:text-purple-700",
    addBtnHoverBg: "hover:bg-purple-50",

    checkboxAccent: "text-purple-600",
    checkboxRing: "focus:ring-purple-500",

    dragBorder: "border-purple-500",
    dragBg: "bg-purple-50",
    dragHoverBorder: "hover:border-purple-400",

    // ── Sidebar ──────────────────────────────────────────────
    sidebarBg: "bg-slate-50",
    sidebarBorder: "border-slate-200",
    sidebarText: "text-slate-500",
    sidebarActiveText: "text-purple-700",
    sidebarActiveBg: "bg-purple-50",
    sidebarActiveBorder: "border-purple-600",
    sidebarHoverBg: "hover:bg-slate-100",
    sidebarIconActive: "text-purple-600",
  },

  green: {
    pageBg: "bg-gradient-to-br from-slate-100 via-slate-50 to-green-50",
    cardBg: "bg-white",
    cardText: "text-slate-800",
    cardBorder: "border-slate-200",
    subtleText: "text-slate-600",

    primaryGrad: "from-green-600 to-emerald-600",
    primarySolid: "bg-green-600",
    primaryHover: "hover:bg-green-700",
    primaryText: "text-green-600",
    primaryLight: "bg-green-50",
    primaryLightHover: "hover:bg-green-100",
    primaryRing: "focus:ring-green-500",
    primaryBorder: "focus:border-green-500",
    primaryHoverBorder: "hover:border-green-400",

    progressGrad: "from-green-500 to-emerald-500",
    stepActiveBg: "from-green-600 to-emerald-600",
    stepCompleteBg: "from-green-500 to-emerald-500",
    stepActiveRing: "ring-green-100",
    progressTrackBg: "bg-slate-200",
    stepInactiveBg: "bg-white",
    stepInactiveBorder: "border-slate-300",
    stepInactiveText: "text-slate-400",
    stepLabelActive: "text-slate-700",
    stepLabelInactive: "text-slate-400",

    modalBg: "bg-white",
    modalHeaderGrad: "from-emerald-100 to-green-50",
    modalHeaderIcon: "text-green-600",
    modalTitle: "text-slate-800",
    modalSubtext: "text-slate-600",
    modalHeaderBorderBottom: "border-green-200",
    modalCloseBtnColor: "text-slate-500",
    modalCloseBtnHover: "hover:text-slate-700",
    modalCloseBtnHoverBg: "hover:bg-slate-100",

    progressSectionBg: "bg-slate-50",
    progressSectionBorder: "border-slate-200",

    footerBg: "bg-slate-50",
    footerBorder: "border-slate-200",
    footerStepText: "text-slate-500",
    footerPrevActiveBg: "bg-white",
    footerPrevActiveText: "text-slate-700",
    footerPrevActiveHover: "hover:bg-slate-100",
    footerPrevDisabledBg: "bg-slate-100",
    footerPrevDisabledText: "text-slate-400",

    nextBtnBg: "bg-green-600",
    nextBtnHover: "hover:bg-green-700",
    submitGrad: "from-green-600 to-emerald-600",
    submitDisabled: "bg-green-400",

    inputBg: "bg-white",
    inputText: "text-slate-900",
    inputPlaceholder: "placeholder-slate-400",
    inputBorder: "border-slate-300",
    labelText: "text-slate-700",
    sectionTitle: "text-slate-800",
    sectionSubtitle: "text-slate-700",
    dividerBorder: "border-slate-200",
    inlineBg: "bg-slate-50",
    removeBtn: "text-slate-400 hover:text-red-500 hover:bg-red-50",

    step1Bg: "bg-green-100",
    step1Icon: "text-green-600",
    step2Bg: "bg-amber-100",
    step2Icon: "text-amber-600",
    step3Bg: "bg-emerald-100",
    step3Icon: "text-emerald-600",
    step4Bg: "bg-teal-100",
    step4Icon: "text-teal-600",

    bannerBg: "bg-green-50",
    bannerBorder: "border-green-500",
    bannerIcon: "text-green-600",
    bannerTitle: "text-green-800",
    bannerText: "text-green-700",

    addBtnText: "text-green-600",
    addBtnHoverText: "hover:text-green-700",
    addBtnHoverBg: "hover:bg-green-50",

    checkboxAccent: "text-green-600",
    checkboxRing: "focus:ring-green-500",

    dragBorder: "border-green-500",
    dragBg: "bg-green-50",
    dragHoverBorder: "hover:border-green-400",

    // ── Sidebar ──────────────────────────────────────────────
    sidebarBg: "bg-slate-50",
    sidebarBorder: "border-slate-200",
    sidebarText: "text-slate-500",
    sidebarActiveText: "text-green-700",
    sidebarActiveBg: "bg-green-50",
    sidebarActiveBorder: "border-green-600",
    sidebarHoverBg: "hover:bg-slate-100",
    sidebarIconActive: "text-green-600",
  },

  dark: {
    pageBg: "bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900",
    cardBg: "bg-slate-800",
    cardText: "text-slate-100",
    cardBorder: "border-slate-700",
    subtleText: "text-slate-400",

    primaryGrad: "from-slate-900 to-slate-600",
    primarySolid: "bg-slate-600",
    primaryHover: "hover:bg-slate-500",
    primaryText: "text-slate-300",
    primaryLight: "bg-slate-700",
    primaryLightHover: "hover:bg-slate-200 hover:text-slate-800",
    primaryRing: "focus:ring-slate-500",
    primaryBorder: "focus:border-slate-500",
    primaryHoverBorder: "hover:border-slate-500",

    progressGrad: "from-slate-500 to-slate-400",
    stepActiveBg: "from-slate-500 to-slate-400",
    stepCompleteBg: "from-slate-500 to-slate-400",
    stepActiveRing: "ring-slate-700",
    progressTrackBg: "bg-slate-700",
    stepInactiveBg: "bg-slate-800",
    stepInactiveBorder: "border-slate-600",
    stepInactiveText: "text-slate-500",
    stepLabelActive: "text-slate-300",
    stepLabelInactive: "text-slate-500",

    modalBg: "bg-slate-800",
    modalHeaderGrad: "from-slate-900 to-slate-700",
    modalHeaderIcon: "text-slate-300",
    modalTitle: "text-slate-100",
    modalSubtext: "text-slate-400",
    modalHeaderBorderBottom: "border-slate-700",
    modalCloseBtnColor: "text-slate-400",
    modalCloseBtnHover: "hover:text-slate-800",
    modalCloseBtnHoverBg: "hover:bg-slate-200",

    progressSectionBg: "bg-slate-900",
    progressSectionBorder: "border-slate-700",

    footerBg: "bg-slate-900",
    footerBorder: "border-slate-700",
    footerStepText: "text-slate-500",
    footerPrevActiveBg: "bg-slate-800",
    footerPrevActiveText: "text-slate-300",
    footerPrevActiveHover: "hover:bg-slate-200 hover:text-slate-800",
    footerPrevDisabledBg: "bg-slate-800",
    footerPrevDisabledText: "text-slate-600",

    nextBtnBg: "bg-slate-600",
    nextBtnHover: "hover:bg-slate-500",
    submitGrad: "from-slate-600 to-slate-500",
    submitDisabled: "bg-slate-700",

    inputBg: "bg-slate-700",
    inputText: "text-slate-100",
    inputPlaceholder: "placeholder-slate-500",
    inputBorder: "border-slate-600",
    labelText: "text-slate-300",
    sectionTitle: "text-slate-100",
    sectionSubtitle: "text-slate-300",
    dividerBorder: "border-slate-700",
    inlineBg: "bg-slate-700",
    removeBtn: "text-slate-500 hover:text-red-400 hover:bg-red-900/30",

    step1Bg: "bg-slate-700",
    step1Icon: "text-slate-300",
    step2Bg: "bg-slate-700",
    step2Icon: "text-slate-300",
    step3Bg: "bg-slate-700",
    step3Icon: "text-slate-300",
    step4Bg: "bg-slate-700",
    step4Icon: "text-slate-300",

    bannerBg: "bg-slate-700",
    bannerBorder: "border-slate-500",
    bannerIcon: "text-slate-300",
    bannerTitle: "text-slate-200",
    bannerText: "text-slate-400",

    addBtnText: "text-slate-300",
    addBtnHoverText: "hover:text-slate-800",
    addBtnHoverBg: "hover:bg-slate-200",

    checkboxAccent: "text-slate-400",
    checkboxRing: "focus:ring-slate-500",

    dragBorder: "border-slate-500",
    dragBg: "bg-slate-700",
    dragHoverBorder: "hover:border-slate-400",

    // ── Sidebar ──────────────────────────────────────────────
    sidebarBg: "bg-slate-900",
    sidebarBorder: "border-slate-700",
    sidebarText: "text-slate-400",
    sidebarActiveText: "text-slate-800",
    sidebarActiveBg: "bg-slate-200",
    sidebarActiveBorder: "border-slate-400",
    sidebarHoverBg: "hover:bg-slate-200 hover:text-slate-800",
    sidebarIconActive: "text-slate-700",
  },
};

export default themeTokens;
